### ISSUE TITLE
Clan Wars

### ISSUE THREAD

**Issue by TheDoctor0** [TheDoctor0/CoDMod#1]
Clans will be extended by new functionality - wars.
Clan leader or deputy can declare war on any other clan by selecting the number of kills as well as a reward for the winner. There is no limit is concurrent wars.
When opposite clan accepts it, half of the reward is taken from both clans balance and a war begins.
It will be in progress to the moment when one of the sides kills players from another clan as many times as the number of kills defined in war declaration.
To allow prioritizing war frags, enemies from opposite clan will have a red model glow, so they can be easily identified.

**Comment by Pi0tRuS** [comment]
Kiedy będą dostępne wojny klanów?

**Comment by TheDoctor0** [comment]
@Pi0tRuS, jeśli znajdę czas, to jeszcze przed końcem tego tygodnia.
