### ISSUE TITLE
Cod mod error

### ISSUE THREAD

**Issue by Pi0tRuS** [TheDoctor0/CoDMod#10]
Cześć,
2 dni temu wyskoczył error log, jednak nie dopisałem "debug" po pluginie codmod.amxx

L 01/31/2019 - 12:43:59: Start of error session.
L 01/31/2019 - 12:43:59: Info (map "de_dust2") (file "addons/amxmodx/logs/error_20190131.log")
L 01/31/2019 - 12:43:59: Invalid array handle provided (0)
L 01/31/2019 - 12:43:59: [AMXX] Run time error 10 (plugin "cod_mod.amxx") (native "ArraySize") - debug not enabled!
L 01/31/2019 - 12:43:59: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).

Teraz mam dopisany, tylko nie wiem jak wywołać ten błąd i nie wiem z jakiego powodu został wywołany.
Jednakże będę sprawdzał, jeżeli dostanę to będzie wiadomo co.

**Comment by TheDoctor0** [comment]
Błąd ten może się pojawiać zaraz po starcie mapy, jeśli serwer od dłuższego czasu nie był restartowany i nie posiada wystarczająco wolnej pamięci. Zazwyczaj w takim wypadku pojawiają się też błędy typu "Thread worker was unable to start" związane z SQLem.
Oczywiście może to być także wywołane po prostu błędem w kodzie, który sprawdza wielkość nieistniejącej tablicy dynamicznej - choć pewnie takie logi pokazywały by się dość często.

Issue pozostawię otwarte, bo ArraySize jest używany w silniku 29 razy.
Jeśli uda ci się złapać error log z włączonym debugiem, będzie można ewentualnie podjąć jakieś kroki, 
aby wyeliminować problem.

**Comment by TheDoctor0** [comment]
Minęły niemal dwa tygodnie, czy ten błąd pojawił się od tego czasu?

**Comment by Pi0tRuS** [comment]
Nie pojawił
