### ISSUE TITLE
Klasa Z Dynamitem

### ISSUE THREAD

**Issue by xHadesSoulx** [TheDoctor0/CoDMod#100]
Bomberman może siebie sam zabić dynamitem

**Comment by TheDoctor0** [comment]
Umiejętności własne nie zadają obrażeń sobie ani członkom drużyny.
Mam serwer developerski z najnowszą wersją (1.5.0) i nic takiego nie ma miejsca.

**Comment by xHadesSoulx** [comment]
Sypie mi logami. A nic nie było zmieniane serwer działał poprawnie aż do dzisiaj 

L 01/22/2020 - 23:14:37: [HAMSANDWICH] Invalid entity (21)
L 01/22/2020 - 23:14:37: [AMXX] Displaying debug trace (plugin "cod_mod.amxx", version "1.5.0")
L 01/22/2020 - 23:14:37: [AMXX] Run time error 10: native error (native "ExecuteHam")
L 01/22/2020 - 23:14:37: [AMXX]    [0] float.inc::operator*(Float:,_:) (line 291)
L 01/22/2020 - 23:14:37: [AMXX]    [1] float.inc::operator*(Float:,_:) (line 291)
L 01/22/2020 - 23:14:37: [AMXX]    [2] cod_mod.sma::_cod_inflict_damage (line 4902)
L 01/22/2020 - 23:14:37: [AMXX]    [3] cod_mod.sma::repeat_damage (line 4888)

**Comment by TheDoctor0** [comment]
Polecałbym przeinstalować serwer i wgrać [BasePack](https://github.com/TheDoctor0/BasePack/releases), a potem CoDa. 
Być może masz wymieszane wersje modułów lub nieprawidłowy hamdata.ini.

**Comment by Pi0tRuS** [comment]
Sprawdzalem nie mam takiego problemu. Stawiam dynamit wybucha I nic. Tak więc problem leży gdzieś w twoich plikach serwerowych.

**Comment by xHadesSoulx** [comment]
Po wgraniu na nowo BasePack błąd zniknął
