### ISSUE TITLE
AMXBANS / SPADOCHRON

### ISSUE THREAD

**Issue by derlius-dev** [TheDoctor0/CoDMod#101]
witam, parę dni temu pojawił się spadochron pod swój przycisk. pobralem i dodalem na serwer lecz po wpisaniu go do plugins-cod serwer nie chce sie odpalic

druga kwestia, posiada ktos poradnik jak wgrac bansa na serwer?

**Comment by Pi0tRuS** [comment]
Skoro nie chce odpalić to dopisz do tego pluginu debug, być może modelu nie wgrałeś?. Poradnik jak wgrać amxbans jest na stronie amxx w dziale amxbans.

**Comment by derlius-dev** [comment]
ReGameDLL version: 5.11.0.421-dev+m
L 01/24/2020 - 09:49:24: -------- Mapchange to de_dust2 --------
[AMXX] Loaded 1 admin from file
[TheDoctor0 - Base Pack] Executing AMX Mod X Configuration File
Scrolling message displaying frequency: 10:00 minutes
L 01/24/2020 - 09:49:25: [cod_mod.amxx] Call of Duty Mod autorstwa O'Zone (v1.5.0).
L 01/24/2020 - 09:49:25: [cod_mod.amxx] Zaladowano 35 klas i 100 przedmiotow.
L 01/24/2020 - 09:49:25: [cod_skins.amxx] Zaladowano 79 skinow dla 9 broni.
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
dlopen failed trying to load:
/home/servers/users/srv62109/.steam/sdk32/steamclient.so
with error:
/home/servers/users/srv62109/.steam/sdk32/steamclient.so: cannot open shared object file: No such file or directory
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit

AKTUALNE ERRORY

**Comment by TheDoctor0** [comment]
Jako, że nie jest to kwestia w żaden sposób powiązana z CoDem zamykam issue.
Lepiej będzie jak otworzysz temat na amxx.pl.
