### ISSUE TITLE
Atuty

### ISSUE THREAD

**Issue by Pi0tRuS** [TheDoctor0/CoDMod#102]
Witam,
Proponuję dodać atuty do owej modyfikacji. Na czym by to polegało?.
Po osiągnięciu x lvl'a mielibyśmy możliwość wyboru jednego z kilku atutów tj. Większy dmg, zmniejszona widzialność, podwójny skok, większą kondycje,  1/x z broni, mniejsza grawitacje oraz inne wymyślone rzeczy. Możliwość kupna atutu za monety na określony czas np 24h. Każda bramka lvl'owa miała by po kilka atutów, zaczynając od najnizeszej załóżmy, że bazujemy na modyfikacji z max 1001lvl, pierwsza bramka zaczynała by się od 201lvl i dodac 3-4 podstawowe atuty do wyboru. Np. Większą kondycję,  zdrowie, grawitacje. Od 501lvl kolejne 3-4 auty np. Zmniejszona widzialność, ciche kroki, większy dmg z broni itd.  Jednak nie wiem czy lepiej żeby się atuty łączyły że sobą z bramek lvl'owych czy od x poziomu są inne atuty i wybieramy z tych na którym osiągnęliśmy dany poziom.

**Comment by TheDoctor0** [comment]
Hej.
Pomysł całkiem mi się podoba, ale jak na razie nie mam niestety na tyle czasu, aby zająć się jego implementacją.
