### ISSUE TITLE
Błąd z dmg (Zapytanie)

### ISSUE THREAD

**Issue by xHadesSoulx** [TheDoctor0/CoDMod#103]
Pisałem już o tym wcześniej lecz informacje pomogły na chwile teraz znów wyskakuje błąd na serwerze a od ponad 20dni nic nie było robione i był spokój a teraz znów mam logi a nawet nie wiem czemu 

Jeśli można proszę o pomoc w rozwiązaniu problemu 

L 02/08/2020 - 19:41:47: [FUN] Player out of range (31)
L 02/08/2020 - 19:41:47: [AMXX] Displaying debug trace (plugin "cod_mod.amxx", version "1.5.0")
L 02/08/2020 - 19:41:47: [AMXX] Run time error 10: native error (native "set_user_footsteps")
L 02/08/2020 - 19:41:47: [AMXX]    [0] cod_mod.sma::reset_attributes (line 3303)
L 02/08/2020 - 19:41:47: [AMXX]    [1] cod_mod.sma::check_player_death (line 4939)
L 02/08/2020 - 19:41:56: Invalid player id 31
L 02/08/2020 - 19:41:56: [AMXX] Displaying debug trace (plugin "cod_mod.amxx", version "1.5.0")
L 02/08/2020 - 19:41:56: [AMXX] Run time error 10: native error (native "client_print_color")
L 02/08/2020 - 19:41:56: [AMXX]    [0] cod_mod.sma::chat_print (line 5566)
L 02/08/2020 - 19:41:56: [AMXX]    [1] cod_mod.sma::player_death (line 2360)
L 02/08/2020 - 19:41:56: [AMXX]    [2] cod_mod.sma::check_player_death (line 4929)

**Comment by TheDoctor0** [comment]
Witaj.
Z tego co widzę w check_player_death brakuje sprawdzenia na wypadek sytuacji, gdy atakujący lub ofiara wyjdzie z serwera w ciągu 0.1s od śmierci - raczej mało prawdopodobne, ale jak widać się zdarza.
Zaraz zrobię commita z fix'em. Jako, że nie jest to coś co w jakikolwiek sposób wpływa na rozgrywkę, nie będę jeszcze wydawał z nim release i wstrzymam się z tym do skończenia #18.
