### ISSUE TITLE
Nieprawidłowo działający cvar cod_accounts_enabled

### ISSUE THREAD

**Issue by masterofencode** [TheDoctor0/CoDMod#104]
Witam otóż wychodze z jedną propozycją aby system kont można było wyłączyć bez obawiania się że silnik moda przestanie działać  bo jeśli wyłączymy konta silnik poprostu nie działa a jeśli jest inne obejście tego to mianowicie jakie?

**Comment by masterofencode** [comment]
Dodam że znikają klasy i wszystko

**Comment by TheDoctor0** [comment]
Witaj.
Zakładam, że nie zaznajomiłeś się specjalnie dobrze z konfiguracją, bo zapewne zauważyłbyś cvar **cod_accounts_enabled**, który pozwala wyłączyć system kont.

**Comment by masterofencode** [comment]
@TheDoctor0  okej nie zauważyłem tego :D  Ale będzie wszystko działać tak?

Ogólnie mam też propozycje mianowicie  napewno kojarzysz killstreak od cypisa mianowicie -->https://amxx.pl/topic/68751-killstreak-134a-14c-wyzwania/ co ty na to by połączyć to razem z tym silnikiem?

**Comment by masterofencode** [comment]
W sensie chodzi mi  czy nie wpłynie to na funkcjonowanie innych pluginów na wymiany klasy exp itp?

**Comment by TheDoctor0** [comment]
Tak, wszystko będzie działać. Ten cvar został właśnie po to dodany 😄 

Co do pluginu KillStreak, raczej nie powinien on w żaden sposób wpłynąć na działanie samego moda. A przynajmniej w teorii, nie przekonasz się dopóki nie przetestujesz sam.

**Comment by masterofencode** [comment]
@TheDoctor0 Gdy wyłączam konta nie można wybrać klas ani nic z tym związnego sklepu itp
czy jak usune to 
`if (!is_user_connected(id) || !cod_check_account(id)) return PLUGIN_HANDLED;`
to coś pomoże?

**Comment by masterofencode** [comment]
Przy wyłaczonych kontach w sensie

**Comment by masterofencode** [comment]
@TheDoctor0  również mam problem bo zmienia losowemu graczowi nick na 60

**Comment by TheDoctor0** [comment]
Powinieneś wyłącznie przestawić cvar, który wymieniłem, ale plugin zostawić włączony.
Pozostałe pluginu muszą mieć dostęp do natywu _cod_check_account_.

Co do zmiany nicku, sam CoD na nicki graczy w żaden sposób nie wpływa, więc zakładałbym, że powoduje to jakiś dodatkowy plugin lub moduł.

**Comment by masterofencode** [comment]
`cod_accounts_enabled "0"`
Gdy ustawie na 0 CoD jako sam w sobie działa lecz nie dostępu do klas, sklepu i innych funkcji znikają poprostu

**Comment by TheDoctor0** [comment]
Myślałem: niemożliwe, dopóki nie zajrzałem w kod systemu kont, gdzie jest kod tego natywu.
Błąd jest w linii 748:
`if (!cvarAccountsEnabled) return 0;`
a powinno być:
`if (!cvarAccountsEnabled) return 1;`

Prawie półtorej roku od publicznego wydania moda i nikt mi tego nie zgłosił - widać wszyscy jednak mają włączony system kont. Dzięki za wykrycie tego buga 😄

**Comment by masterofencode** [comment]
@TheDoctor0  nie ma sprawy :)
