### ISSUE TITLE
Zapytanie o item

### ISSUE THREAD

**Issue by xHadesSoulx** [TheDoctor0/CoDMod#106]
Witam ja piszę z pytaniem jak stworzyć item premium że tylko osoba z daną flaga może go dropnąć a osoba która jej niema dostanie inny w przypadku jego zdobycia

Wcześniej zajmowałem się diablo modami więc tam widziałem o co chodzi lecz tutaj nie za bardzo

**Comment by TheDoctor0** [comment]
Wystarczy zgodnie z [dokumentacją](http://codmod.5v.pl/cod/cod_register_item) wybrać flagę, na którą item ma być dostępny.
Przykładowo jeśli powiedzmy przedmiot Bezlik Amunicji miał być dostępny tylko dla osób z flagą t (VIP), to mogłoby to wyglądać np. tak:
```c
#include <amxmodx>
#include <cod>

#define PLUGIN "CoD Item Bezlik Amunicji (VIP)"
#define VERSION "1.0"
#define AUTHOR "O'Zone"

#define NAME        "Bezlik Amunicji (VIP)"
#define DESCRIPTION "Twoja amunicja sie nie konczy"
#define FLAG        ADMIN_LEVEL_H

public plugin_init()
{
	register_plugin(PLUGIN, VERSION, AUTHOR);

	cod_register_item(NAME, DESCRIPTION, .flag=FLAG);
}

public cod_item_enabled(id, value)
	cod_set_user_unlimited_ammo(id, true, ITEM);
```
