### ISSUE TITLE
Item obcy

### ISSUE THREAD

**Issue by xHadesSoulx** [TheDoctor0/CoDMod#107]
Dziś jak grałem na serwie i spotkałem się z błędem itemu 
 obcy który  zabija siebie i towarzyszy razem z przeciwnikiem jeśli są w polu rażenia

**Comment by TheDoctor0** [comment]
Hej.
Właściwie przedmiot działa dokładnie w sposób, w jaki został napisany.
Eksplozję generuje zabity, więc obrażenie otrzymują jego przeciwnicy.

Niemniej, jest to raczej dość mylące, więc przepiszę ten plugin, 
aby eksplozja była generowana w miejscu śmierci gracza, 
ale obrażenia zadawał gracz, który zdobył fraga.
