### ISSUE TITLE
Zapytanie

### ISSUE THREAD

**Issue by xHadesSoulx** [TheDoctor0/CoDMod#108]
Wiem że mam wiele pytań ale no niestety znam się na tym tak w 30% moje pytanie dotyczy itemu czy w silniku lub itemach jest możliwość dodania warunku random drop czyli losowa szansa na wypadnięcie itemu.
Chodzi mi o itemy które lecą częściej a niektóre trudniej 
np item cień szansa na zdobycie to 1 na 20 a item obcy 1 na 5 więc mamy szanse zdobyć pod rząd trzy razy obcy a raz cień

sorki za pisownie ale nie jest moją mocną stroną

**Comment by TheDoctor0** [comment]
Hej.
Z poziomu samego silnika na ten moment nie ma takiej opcji, bo wymagała by ona zdefiniowana "rzadkości" w natywie cod_register_item.

Niemniej jak najbardziej można do tego wykorzystać forward cod_item_check.
Przykładowo w taki sposób:
```
public cod_item_check(id)
	return random_num(1, 3) != 1 ? COD_CONTINUE : COD_STOP;
```
Sprawi to, że ten przedmiot będzie 3 razy trudniejszy do zdobycia, bo przy każdym jego wylosowaniu w silniku tutaj dodatkowo losowana jest wartość od 1 do 3 i musi wynosić 1.
