### ISSUE TITLE
Pomysł

### ISSUE THREAD

**Issue by xHadesSoulx** [TheDoctor0/CoDMod#109]
Witam mój pomysł polega na dodaniu do cod mod funkcji która jest na bf1 
mini innymi ranga za czas gry moim zdaniem jest to fajny pomysł dużo graczy podoba się to na bf1 i też chciałbym żeby owy system był na cod mod jeśli jest możliwość  wprowadzenie jeszcze top 15 do tego lub dodać wzmiankę o randze w top czasu

**Comment by TheDoctor0** [comment]
Top15 czasu gry jest dostępne od niemalże początku tego moda. Komendy:
```
new const commandTopTime[][] = { "topczas", "say /ttop15", "say_team /ttop15", "say /toptime", "say_team /toptime", "say /ctop15", "say_team /ctop15", "say /topczas", "say_team /topczas" };
```

> mini innymi ranga za czas gry moim zdaniem jest to fajny pomysł dużo graczy podoba się to na bf1

Nie widzę specjalnie sensu dopisywania takiej funkcjonalności do ogólnej wersji moda.

Jeśli chcesz coś takiego posiadać rozbuduj plugin CoD Stats lub w ogóle napisz osobny plugin dla rang za czas wykorzystując natyw [cod_get_user_time](http://codmod.5v.pl/cod/cod_get_user_time).
