### ISSUE TITLE
Status admina w statystykach

### ISSUE THREAD

**Issue by Pi0tRuS** [TheDoctor0/CoDMod#11]
Znalazłem kolejny błąd

Nie zlicza czasu spędzonego przez admina. W ogóle nie przypisuje flagi adminowi na "1" w bazie danych i motd top15 czasu adminów jest pusty.

Oraz napiszę tutaj propozycję, żeby dodać top15 lvl'a. Mniej więcej żeby motd wyglądał następująco

Nick        Klasa         Poziom       Honor         Klan

**Comment by TheDoctor0** [comment]
Flaga admina jest w pluginie statystyk ustawiana tylko raz, w _client_authorized_, co zakładam, że może być niewystarczające na serwerach np. korzystających z ładowania adminów z bazy AmxBans.
Przemyślę, czy dodać wychwytywanie multi-forwardu _amxbans_sql_initialized_ wysyłanego przez AmxBans po załadowaniu/przeładowaniu adminów, czy po prostu dodam każdorazowe sprawdzanie posiadania odpowiedniej flagi.

Masz na myśli już istniejące Top 15 poziomów zaimplementowane w silniku? Komendy:
```new const commandTop[][] = { "top", "say /toplvl", "say_team /toplvl", "say /toplevel", "say_team /toplevel", "say /toppoziom", "say_team /toppoziom", "say /ltop15", "say_team /ltop15", "say /ptop15", "say_team /ptop15" };```

PS. Propozycje prosiłbym zgłaszać jako osobne Issue, bo łatwiej jest mi wtedy nimi zarządzać, przypisywać do projektów i oznaczać ich statusy.

**Comment by Pi0tRuS** [comment]
Mam amxbansa, ale adminów czyta z users.ini nie z amxbansa

**Comment by Pi0tRuS** [comment]
Nie będe tworzył nowego issues, jednak zauważyłem, że przed końcem czasu mapy, plugin nie daje medali oraz expa za najlepsze statystyki na mapie.

**Comment by TheDoctor0** [comment]
Silnik korzysta z eventu SVC_INTERMISSION (message_intermission) do wychwycenia końca mapy.
Nie jest on wywoływany przy zmianie mapy korzystając z komend amx_map lub changelevel,
więc jeśli korzystasz z manadżera map, który do zmiany mapy wykorzystuje komendę changelevel 
(a robi to praktycznie każdy), upewnij się, że wywołuje on przed tym event SVC_INTERMISSION.

**Comment by TheDoctor0** [comment]
https://forums.alliedmods.net/showthread.php?t=159640:
``
Messages sent with message_begin() cannot be hooked.
The message has to be sent with emessage_begin() (and appropriate e*() functions instead of the normal ones) to be hooked. 
``

Zamień
```
message_begin( MSG_ALL, SVC_INTERMISSION );
message_end();
```
na:
```
emessage_begin(MSG_ALL, SVC_INTERMISSION);
emessage_end();
```
i powinno działać bez problemu.

**Comment by Pi0tRuS** [comment]
Nie skompiluje się plugin nie wiem dlaczego

**Comment by TheDoctor0** [comment]
Jeśli nie chce się skompilować, to chyba rzuca jakimś błędem, czyż nie?

Skompilowałem go u siebie lokalnie bez żadnego problemu: [Download](https://ufile.io/lx7jc).

**Comment by Pi0tRuS** [comment]
Działa, dostaje medale oraz expa, jednak mapa za szybko się zmienia i chciałbym żeby wydłuzyć czas zmiany mapy. A co do błędu gdy dodałem to to w kompilatorze mam błąd "Invalid function or declaration" w pierwszej linijce kodu galileo. I gdy chcę zmienić mp_chattime z 3 na 6 to nie skompiluje pluginu

**Comment by TheDoctor0** [comment]
To już nie dotyczy bezpośrednio samego mod'a, więc z tym problemem załóż temat na amxx.pl.

**Comment by Pi0tRuS** [comment]
Wykonałem poprawkę pluginu na fix tego pluginu jednak dalej nie ma nic w motd. W bazie danych widzę, że przypisało mi admina na numer "8"

**Comment by TheDoctor0** [comment]
Możesz bez obaw wgrać plugin statystyk z wersji 1.2.0, bo poza fixami i dodaniem opcji zemsty nic w nim się dodatkowo nie zmieniło. Samą zemstę można wyłączyć cvarem cod_revenge_enabled "0".

**Comment by Pi0tRuS** [comment]
Displaying debug trace (plugin "cod_mod.amxx", version "1.0.0")
L 02/03/2019 - 12:49:39: [AMXX] Run time error 10: native error (native "cod_get_user_time_text")
L 02/03/2019 - 12:49:39: [AMXX]    [0] cod_mod.sma::show_info (line 2541)

**Comment by Pi0tRuS** [comment]
[AMXX] Run time error 10 (plugin "cod_honor.amxx") (native "cod_get_user_class") - debug not enabled!
L 02/03/2019 - 12:50:04: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).

**Comment by TheDoctor0** [comment]
Pełny debug trace powinien zawierać co najmniej 4 linijki, wrzuciłeś 3.
Widzę, że silnik wyrzuca błąd użycia natywu cod_get_user_time_text, który nadal jest w pluginie statystyk i nie był w żaden sposób modyfikowany. 
No a to z kolei powoduję lawinę błędów z reszty pluginów, które nie mogą użyć natywów z silnika.

**Comment by TheDoctor0** [comment]
Logi AMXX'a w większości przypadków bardzo dokładnie wskazują przyczynę problemu, wystarczy je przeanalizować. Wgrałem na serwer testowy wersję 1.0 i wrzuciłem plugin statystyk z 1.2, od razu w konsoli ukazał mi się błąd:
```
[AMXX] Plugin "cod_stats.amxx" failed to load: Plugin uses an unknown function (name "cod_log_error") - check your modules.ini.
```
Wystarczy więc sprawdzić, gdzie w statystykach użyty jest ten natyw i zastąpić go chociażby używając funkcji log_to_file, która była wykorzystywana wcześniej.

Kolejne wersje są wypuszczane w jakimś celu, jednym z nich są poprawki właśnie, a od wersji 1.0 do 1.2 była ich masa. Stąd też ja rekomenduję zrobienie aktualizacji - która swoją drogą nie powinna zająć więcej niż 15min, bo wystarczy wgrać wszystko, wyczyścić całą bazę lub usunąć tylko tabele klanów (wymagane) i przywrócić zmiany w zrobione konfiguracji. Jeśli chcesz zostać przy starszej wersji, poprawki musisz wprowadzać na własną rękę.

**Comment by Pi0tRuS** [comment]
Możesz mi powiedzieć jakiej wersji rehlds i amxx używałeś do wersji 1.2?. W moim przypadku było tak, że gdy miałem wersję 1.1 to miałem co chwilę segmention fault bez powodu a na wersji 1.0 wszystko jest stabilne.

**Comment by TheDoctor0** [comment]
```
ReHLDS version: 3.4.0.668-dev
Build date: 09:47:42 Sep 29 2018 (1631)
Build from: https://github.com/dreamstalker/rehlds/commit/89be216
```

```
AMX Mod X 1.9.0.5235 (http://www.amxmodx.org)
Built from: https://github.com/alliedmodders/amxmodx/commit/6c53524
```
