### ISSUE TITLE
Pytanie o Skile

### ISSUE THREAD

**Issue by xHadesSoulx** [TheDoctor0/CoDMod#110]
mam taką sprawę jest coś takiego jak podpalenie , trucie i pojawia się to tylko osobie która ma efekt gdzie mam do pisać warunek żeby wyświetlało się model podpalenia żeby było widać że ta osoba się pali 

mam to zrobić po stronie silnika czy klasy ?

**Comment by TheDoctor0** [comment]
Witaj.
Jeśli chcesz dodać takie efekty, to zdecydowanie zalecałbym zrobienie tego w silniku, żeby nie robić tego w każdej klasie. W obu przypadkach zajrzałbym do funkcji repeat_damage.
Od razu jednak ostrzegam, że nie jest to tylko kwestia dodania/zmiany jakiegoś warunku - musisz tutaj faktycznie stworzyć nowe efekty, np. z użyciem spritów.
Ja takowych nie dodawałem, bo zwyczajnie uznałem je za zbędne.
