### ISSUE TITLE
Obsługa smssklep

### ISSUE THREAD

**Issue by dinowy** [TheDoctor0/CoDMod#116]
Siemka korzystam z tego sklepu https://github.com/gammerce/sklep-sms/wiki/Konfiguracja i mam problem bo nie moge dodac uslugi cod_honor i cod_exp z Twojego githuba. Nie chce sie przekompilowac - moglbys pomoc? :)

**Comment by TheDoctor0** [comment]
Witaj.
Wrzuć logi błędów z kompilacji, żebym jakkolwiek był ci w stanie pomóc.

**Comment by dinowy** [comment]
Problem jest taki że już usunąłem te pliki - nie posiadasz może ich skompilowanych? Żeby dodać honor i exp do sklepu?
