### ISSUE TITLE
Błąd podczas tworzenia klanu

### ISSUE THREAD

**Issue by Rohatcengizhanbucak** [TheDoctor0/CoDMod#120]
Próba utworzenia nowego klanu z poziomu gry daje błąd

[CoD] Podczas tworzenia klanu wystapil nieoczekiwany blad.

**Comment by TheDoctor0** [comment]
@Rohatcengizhanbucak sprawdź logi błędów, powinien być tam dokładny powód wystąpienia tego problemu.

**Comment by Rohatcengizhanbucak** [comment]
Przepraszam, mój polski język jest zły. Myślę, że nie sądzisz, że planujesz wspierać, o ile rozumiem, założyliśmy go bez żadnych problemów, ale nie mogliśmy otworzyć klanu

**Comment by Rohatcengizhanbucak** [comment]
Teraz, kiedy rozumiem, co masz na myśli, wyrzucam to

L 05/03/2023 - 22:41:58: [CoD Accounts] SQL Query Error. [1698] Access denied for user 'user'@'localhost'
L 05/03/2023 - 22:41:58: [CoD Honor System] SQL Query Error. [1698] Access denied for user 'user'@'localhost'
L 05/03/2023 - 22:41:58: [CoD Stats] SQL Query Error. [1698] Access denied for user 'user'@'localhost'
L 05/03/2023 - 22:41:58: [CoD Clans] SQL Query Error. [1698] Access denied for user 'user'@'localhost'
L 05/04/2023 - 12:48:12: [CoD Clans] SQL Query Error. [1364] Field 'honor' doesn't have a default value

**Comment by TheDoctor0** [comment]
@Rohatcengizhanbucak you need to configure MySQL database cvars that are available in https://github.com/TheDoctor0/CoDMod/blob/master/resources/addons/amxmodx/configs/cod_mod.cfg.
