### ISSUE TITLE
2 Slot for Item/Perk

### ISSUE THREAD

**Issue by swtkiptr** [TheDoctor0/CoDMod#122]
Hello,

Thanks for great mod btw. Any clue how to make 2 slot for perk/item?

**Comment by TheDoctor0** [comment]
Hey @swtkiptr.

You would pretty much duplicate the logic for item handling to do that, which requires you to be skilled in AMXX and implement it.

If you don't have such skills, I would suggest asking about it for example on https://forums.alliedmods.net/. Maybe you will find a kind person there to do it for you :smile:

**Comment by swtkiptr** [comment]
Yes, already figure out by doubling PLAYER_ITEM2 and some code. after all its work perfectly.
