### ISSUE TITLE
Problem z czasami adminów ciąg dalszy

### ISSUE THREAD

**Issue by Pi0tRuS** [TheDoctor0/CoDMod#19]
Cześć,
Tworzę znowu nowy issues. Przeinstalowałem cały serwer, wgrałem całą nową paczkę wersję 1.2. W menu statystyk w ogóle nie pokazuje się opcja "czasy adminów"

**Comment by TheDoctor0** [comment]
Zarówno VIP jak i plugin statystyk do wykrywania przypisanych flag używają standardowego _client_authorized_ jak i forwardu z AmxBans _amxbans_admin_connect_.

```if (playerStats[id][ADMIN]) menu_additem(menu, "\wCzas \rAdminow \y(/adminczas)", "2");```
Jeśli nie widzisz tej opcji, to znaczy, że nie wykryto, abyś posiadał flagę ADMIN_BAN.

Możesz przetestować wykrywanie przypisanych flag np. zamieniając:
```
public client_authorized_post(id)
    playerStats[id][ADMIN] = (get_user_flags(id) & ADMIN_FLAG) ? 1 : 0;
```
na:
```
public client_authorized_post(id)
{
	new name[MAX_NAME];

	get_user_name(id, name, charsmax(name));

	playerStats[id][ADMIN] = (get_user_flags(id) & ADMIN_FLAG) ? 1 : 0;

	log_amx("Gracz: %s | Admin: %s", name, playerStats[id][ADMIN] ? "Tak" : "Nie");
}
```
i sprawdzając, co pokaże się w logach.

**Comment by TheDoctor0** [comment]
O ile w międzyczasie nie następuje jakieś przeładowanie flag, które pozbawia cię wymaganej flagi, kolumna admin w bazie zostanie wypełniona przy najbliższym zapisie danych: po respawnie, końcu mapy lub wyjściu z serwera.

**Comment by Pi0tRuS** [comment]
No niestety nic się takiego nie dzieje. Np. mój czas gry, lastvisit się aktualizują a admin dalej na "0" i tak samo w sytuacjach które powiedziałeś, po respawnie końcu mapy lub wyjściu z serwera.

**Comment by TheDoctor0** [comment]
Funkcja _client_authorized_post_ jest jedynym miejscem, gdzie wartość **playerStats[id][ADMIN]** jest modyfikowana. 
Jeśli po przypisaniu flag widzisz w menu opcję Czas Adminów i możesz użyć komendy /czasadmin, to wartość ta powinna być potem bez problemu zapisana. Jednakże jeśli nie masz do nich dostępu, sprawdź niżej w logach, czy przypisanie flag nie następuje drugi raz, resetując wcześniej przypisaną wartość.
Mam na serwerze testowym wersję 1.2 z uprawnieniami admina ładowanymi z users.ini (bez AmxBans) i wszystko działa jak należy.

**Comment by Pi0tRuS** [comment]
Serwer mam świeży, wgrana tylko paczka żadnych pluginów i przeładowania adminów oraz brak amxbans. Coś jest po prostu nie tak

**Comment by Pi0tRuS** [comment]
Zmieniłem ręcznie w bazie danych moją kolumnę "Admin" na "1" po zmianie mapy wraca na "0"

**Comment by TheDoctor0** [comment]
Oczywiście, że wartość zostanie nadpisana, jeśli sam plugin przy zapisie danych ma informację, że nie posiadasz wymaganej flagi.

**Comment by Pi0tRuS** [comment]
No ale Ja mam wszystkie flagi admina, więc ?

**Comment by TheDoctor0** [comment]
Zapewne odnosi się to do [tego](https://github.com/TheDoctor0/CoDMod/commit/b645d308a06dcdd289d96f83c2e67e14bea938cc) commita, który poprawia możliwość zresetowania wartości **playerStats[id][ADMIN]**, gdy _client_putinserver_ zostanie wywołane po _client_authorized_ - wszystko zależy od szybkości ładowania uprawnień. Pobierz sobie świeży release wersji 1.2. i problem zniknie.

**Comment by Pi0tRuS** [comment]
Pobrałem wszystkie aktualne pliki, zaczęło działać :)
