### ISSUE TITLE
Problem z punktami statystyk

### ISSUE THREAD

**Issue by Pi0tRuS** [TheDoctor0/CoDMod#20]
Kolejny błąd,
Mam maksymalny lvl czyli 501 dostałem 500 punktów więc je rozdałem do statystyk. Po zmianie mapy mam znowu 500 punktów które muszę dodać od nowa i tak co zmianę mapy.

**Comment by Pi0tRuS** [comment]
kolejny lecz już mały błąd. Dodaję maks punktów do życia, w say wyskakuje "
[CoD] Maksymalny poziom sily osiagniety!"

**Comment by Pi0tRuS** [comment]
Dodam jeszcze, że gdy wykorzystam wszystkie punkty, to zapisują się w bazie danych lecz gdy zmienię mapę i będe miał znowu 500 punktów to resetują się.

**Comment by TheDoctor0** [comment]
Oba błędy zostały poprawione. Jako, że nie są krytyczne, na razie wstrzymam się jeszcze przed wydaniem release oznaczonego 1.2.1, aż nazbiera się nieco więcej poprawek.
Jeśli chcesz, możesz sobie pobrać silnik z fixem bezpośrednio z brancha [master](https://github.com/TheDoctor0/CoDMod/archive/master.zip), skompilować i wrzucić na serwer.
