### ISSUE TITLE
Wojny klanów problem

### ISSUE THREAD

**Issue by Pi0tRuS** [TheDoctor0/CoDMod#21]
Pierwsz sprawa parametry wojny.

1. Wysokość nagrody w Euro?. Waluta w klanie to honor no bynajmniej mi się tak wydaje.
2. Mogę wypowiedzieć wojne klanowi którego nie ma. Wygląda to tak:

Ustawiam parametry wojny -> klikam wypowiedz wojne -> wybieram klan z którym chcę prowadzić wojnę i mam do wyboru:

1. (Członkowie: 0 | Honor: 0.00 )

Wybieram tą opcję, zgadzam się na liczbę fragów i nagrodę która o dziwo tutaj jest waluta Honor i wypowiadam wojnę klanowi którego nie ma.

**Comment by TheDoctor0** [comment]
O której pobierałeś release? Pytam z racji tego, iż był on wydawany dwukrotnie, drugi raz wraz z poprawkami typu hotfix, w tym jednej zmieniającej string "Euro" pozostawiony po częściowej adaptacji kodu wojen z mojego prywatnego cs:go moda.

**Comment by Pi0tRuS** [comment]
Pierwszą edycję 1.2. Rozumiem, że fixy naprawiają te 2 błędy?

**Comment by TheDoctor0** [comment]
Jeden z commitów poprawia pierwszy błąd.
Drugi nie został wcześniej wykryty i z tego co widzę wynika ze specyfiki użytego zapytania do bazy, które w przypadku braku wyników zwróci jeden wiersz z pustymi (nullowymi) wartościami. Jestem właśnie w trakcie pisania odpowiedniego fixa.

**Comment by Pi0tRuS** [comment]
Waluta euro naprawiona, tylko właśnie wypowiedzenie wojny klanowi którego nie ma jest jeszcze aktualne.
