### ISSUE TITLE
Koszt nazwy klanu

### ISSUE THREAD

**Issue by Pi0tRuS** [TheDoctor0/CoDMod#23]
Wychodzę z propozycją żeby dodać koszt nazwy klanu z cvarem gdyż  niektórzy potrafią zmienić nazwę klanu kilka razy na mapę bądź w jakiś sposób zablokować np do 3 razy

**Comment by TheDoctor0** [comment]
Ciekawa propozycja.
Myślę, że faktycznie koszt zmiany nazwy klanu zdecydowanie zredukuje takie sytuacje.
Oczywiście nie widzę także problemu z dodaniem blokady jednej zmiany klanu na mapę.
