### ISSUE TITLE
Dodatkowy bonus w klanie

### ISSUE THREAD

**Issue by Pi0tRuS** [TheDoctor0/CoDMod#24]
Cześć,
wpadłem na pomysł żeby dodać dodatkowy bonus do klanu czyli większy % zdobywanego honoru bądź expa, lub jakąś inną statystykę. 

Oraz myślałem nad nagrodą za wygraną wojnę, może by tak doświadczenie dla wszystkich graczy klanu oprócz fragów i honoru.

Może by tak dodać nowy nóż z jakąś regeneracją HP przy kucaniu dla vipa?

**Comment by TheDoctor0** [comment]
Przyznam szczerze, że sam ostatnio zastanawiałem się nad dodatkowym bonusem dla klanu w postaci procentowego bonusu do expa właśnie. Także najprawdopodobniej takowy doimplementuję.

Hmm... zakładam, że miałaby to być dodatkowa zachęta do prowadzenia klanowych wojen? Przemyślę sprawę.

Jakiś dodatkowy nóż specjalnie dla VIPów nie jest złym pomysłem, choć regeneracja HP wydaje się zbyt over-powered w stosunku do drobnych bonusów statystyk. Tutaj też do przemyślenia.
