### ISSUE TITLE
Spadochron?

### ISSUE THREAD

**Issue by Pi0tRuS** [TheDoctor0/CoDMod#25]
Cześć,
użycie skilla jest pod domyślnym klawiszem "e" i gryzie się ze spadochronem, byłaby możliwość użycia "z" w przypadku skilla i żeby spadochron został standardowo na "e" ?. Jeżeli tak to może krótka instrukcja ?

**Comment by TheDoctor0** [comment]
Dokładnie to samo pytanie padło już w [temacie](https://amxx.pl/topic/162311-call-of-duty-mod-by-ozone/?p=756540) na amxx.pl

**Comment by Pi0tRuS** [comment]
Nie wiem czy to dobrze zrobiłem, może się wypowiesz. 

Zamieniłem +use na:

register_clcmd("radio3", "use_class");
register_clcmd("radio3", "use_item");

usunąłem dźwięk w public sound_emit. Skille działają pod klawiszem "c" czyli standardowe radio3

**Comment by eryk172** [comment]
Dokładnie, radio3 to klawisz "c" , radio 2 to x, radio1 to z. Oczywiście standradowo tak jest, ale inny gracz moze miec innego binda pod te klawisze więc warto dać o tym informacje. Jeżeli sobie nie poradziłeś, napisz do mnie a podrzucę Ci gotowy kod z uzyciem skilla na klawiszu z/x/c
