### ISSUE TITLE
Error log clans

### ISSUE THREAD

**Issue by Pi0tRuS** [TheDoctor0/CoDMod#26]
L 02/10/2019 - 11:28:38: Log file started (file "cstrike/addons/amxmodx/logs/cod_mod.log") (game "cstrike") (amx "1.9.0.5241")
L 02/10/2019 - 11:28:38: [CoD Clans] Threaded query failed. Error:  (1242)
L 02/10/2019 - 13:10:53: [CoD Clans] Threaded query failed. Error:  (1242)
L 02/10/2019 - 13:11:07: [CoD Clans] Threaded query failed. Error:  (1242)
L 02/10/2019 - 14:11:50: [CoD Mod] Could not connect to SQL database. Error: Can't connect to MySQL server on 'sql.pukawka.pl' (4) (2003)

**Comment by eryk172** [comment]
Złe dane do bazy. U mnie działa

**Comment by Pi0tRuS** [comment]
dane do bazy są dobre, lecz czasami wywala taki error log.

**Comment by Pi0tRuS** [comment]
Problem jest z top15 klanów, dlatego wywala error log Threaded query failed. Error: (1242). MOTD w ogóle się nie otwiera.

**Comment by eryk172** [comment]
[CoD Clans] Threaded query failed. Error: (1242)

Dokładnie mam ten sam błąd, jeżeli są dwa klany na serwerze. Przy jednym nie ma problemu

**Comment by TheDoctor0** [comment]
> 
> 
> [CoD Clans] Threaded query failed. Error: (1242)
> 
> Dokładnie mam ten sam błąd, jeżeli są dwa klany na serwerze. Przy jednym nie ma problemu

I to już jest bardzo konkretna informacja.
Jeśli pamięć mnie nie myli, SQL error 1242 to subquery w selectcie zwracające więcej niż jeden rezultat.

Przyjrzałem się temu i jak widzę subquery zliczające członków klanu robi to na kolumnie `id`, której w tabeli `cod_clans_members` nawet nie ma.

Szybki fix, który poszedł w commicie (różnica wyłącznie w `COUNT(clan)`):
```formatex(queryData, charsmax(queryData), "SELECT a.id, a.name, a.honor, a.kills, a.level, a.wins, (SELECT COUNT(clan) FROM `cod_clans_members` WHERE clan = a.id) as members FROM `cod_clans` a ORDER BY kills DESC LIMIT 15");```
zamiast:
```formatex(queryData, charsmax(queryData), "SELECT a.id, a.name, a.honor, a.kills, a.level, a.wins, (SELECT COUNT(id) FROM `cod_clans_members` WHERE clan = a.id) as members FROM `cod_clans` a ORDER BY kills DESC LIMIT 15");```

Jeśli chcecie, możecie go wypróbować i dać znać czy faktycznie problem leżał właśnie tutaj - jako, że ja w tej chwili nie mam takiej możliwości.

**Comment by Pi0tRuS** [comment]
Działa

**Comment by TheDoctor0** [comment]
Świetnie, w takim razie zrobię potem szybki re-release z tym hot-fixem (trochę to za mało na kolejną wersję), żeby inni nie mieli już tego problemu.
