### ISSUE TITLE
Rework skinów broni

### ISSUE THREAD

**Issue by Pi0tRuS** [TheDoctor0/CoDMod#27]
Witam,
Proponuję dodać motd  z obrazkiem skina  broni żeby nie szukać po googlach jak on wygląda. Możesz  tylko zrobić bazę do tego A wygląd broni zrobi sobie każdy samodzielnie

**Comment by eryk172** [comment]
Spoko pomysł, widziałem to na CS:GO modach

**Comment by TheDoctor0** [comment]
Myślę, że przyda się to graczom.
Właściwie nie powinno być problemem z dodaniem tego, jeden dodatkowy parametr w configu skinów ze ścieżką do obrazka i dodanie możliwości obejrzenia go w MOTD przed kupnem.

**Comment by TheDoctor0** [comment]
Wymyśliłem nawet lepszy sposób na sprawdzenie wyglądu skina, który nie wymaga mozolnego robienia screenów. 
Podczas zakupu dodałem dodatkowe menu z potwierdzeniem, gdzie poza możliwością kupna, można wypróbować skina przez uaktywnienie go jako skin dla każdej broni na 5 sekund.
Plugin został też nieco zrefaktoryzowany, usprawniona została logika ustawiania skinów i przebudowano strukturę bazy danych. Wszystkie zmiany zostaną wydane w wersji 1.3.0.
