### ISSUE TITLE
Kolejkowanie użycia multi-bindów min, dynamitów etc.

### ISSUE THREAD

**Issue by Pi0tRuS** [TheDoctor0/CoDMod#28]
Cześć,

w liście bindów jest napisane, że można zbindować pod jeden klawisz kilka skilli np. minę, dynamit. Jednak po zbindowaniu kilku rzeczy bindy nie działają.

**Comment by TheDoctor0** [comment]
Bindujesz sobie przykładowo: bind "z" "+rocket;+mine;+dynamite;+medkit"?

**Comment by Pi0tRuS** [comment]
Tak I nie działa

**Comment by TheDoctor0** [comment]
Sprawdziłem na serwerze testowym dodając sobie customową komendą jednocześnie po jednej rakiecie, minie, dynamicie i apteczce - bindy działają jak powinny.

**Comment by Pi0tRuS** [comment]
Zadziałało ale tak jak mówisz pasowaloby zrobić jakieś kolejkowanie bo wywala  wszystkie Dhud  na raz bo wszystkiego chce użyć
