### ISSUE TITLE
Efekt uboczny nielimitowanego ammo i eliminatora rozrzutu

### ISSUE THREAD

**Issue by Pi0tRuS** [TheDoctor0/CoDMod#29]
Cześć,
Grając z tym perkiem który daje p90, nieograniczoną ilość amunicji i całkowity eliminator rozrzutu, gram jak na aimie. Strzelam pełen magazynek a celownik lata we wszystkie strony.

**Comment by TheDoctor0** [comment]
Gotowe klasy i przedmioty są jedynie przykładami, które obrazują jak poprawnie korzystać z możliwości silnika i zachęcam do tworzenia własnych.
Jeśli uważasz, że ten przedmiot jest zbyt OP, zmodyfikuj go pod swoje potrzeby lub nie używaj go wcale.

**Comment by Pi0tRuS** [comment]
Nie uważam że przedmiot jest OP tylko eliminator  rozrzutu  nie działa w nim poprawnie

**Comment by TheDoctor0** [comment]
Eliminator rozrzutu użyty w tym przedmiocie to dokładnie to samo co w samym przedmiocie "Eliminator Rozrzutu" i tak po prostu działa na P90. Możesz to zresztą sprawdzić chociażby na klasie Saper dodając sobie sam Eliminator Rozrzutu.

**Comment by Pi0tRuS** [comment]
Jestem na klasie Saper z p90. Dałem sobie eliminator rozrzutu. Działa jak powinno.
Dam sobie perk boskie p90 i celownik rusza się na wszystkie strony. Czyli coś jest nie tak.

**Comment by TheDoctor0** [comment]
Jeśli masz na myśli te chwilowe przeskoki (jeden/dwa naboje zazwyczaj lecące znacznie wyżej), to wynika z połączenia, jest to efekt uboczny wynikający z działania eliminatora rozrzutu w połączeniu z nielimitowanym ammo (przez ciągłe napełnianie magazynka). Czy o to "ruszanie się celownika na wszystkie strony" ci chodzi?

**Comment by Pi0tRuS** [comment]
tak o to. Czyli jest to spowodowane nielimitowanym ammo i jest to efekt uboczny z którym nie da się nic zrobic?

**Comment by TheDoctor0** [comment]
Nie jest wykluczone, że dałoby się pozbyć tego efektu przez głębszą optymalizację kodu obu skillów - a szczególnie samego eliminatora. Nie ma co ukrywać, że jest to bardzo małe nieudogodnienie, mimo wszystko spróbuję.
