### ISSUE TITLE
Wyłączenie modeli broni

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#34]
Prosze o dodanie opcji wylaczenie modeli trzymanych broni na komende/menu.

Łatwiej się wyłapuje cheatera, jesli gra on na standradowym modelu

**Comment by TheDoctor0** [comment]
Dodanie możliwości wyłączenia sobie modeli broni to żaden problem,
aczkolwiek podczas obserwowania gracza widoczny jest skin ustawiony przez niego.
W takim przypadku należałoby przywrócić domyślny skin gracza na życzenie admina,
co sam gracz oczywiście by zauważył i byłoby to oczywiste dla niego, że jest obserwowany.

**Comment by eryk172** [comment]
Nie ma co się nad tym głownić, aczkolwiek jeśli by pojawił się jakiś genialny sposób na to zeby ukryć skiny wszystkich graczy dla osoby która chce zeby było ukrytę to można dodać.
Teraz to nie jest jakies koniecznie :) 

Pozdr

**Comment by TheDoctor0** [comment]
Po analizie, jak podejrzewałem, niemożliwe jest ukrycie skinów pozostałych graczy, bo podczas spectowania danego gracza ogląda się jego byt broni wraz z ustawionym modelem.
