### ISSUE TITLE
Ikony

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#35]
Zostaje ikona na następną rundę, ta ze znakiem zapytania.
Testowalem jesli bylo 2vs1. 
Wypadla skrzynka z gracza, ktorej nikt nie podniosl ( oczywiscie nie bylo przy niej ikonki)
W nastepnej rundzie pojawila sie ikonka w miejscu skrzynki, a skrzynka znikla.

**Comment by eryk172** [comment]
Dodam ze wystepuje to tylko, gdy nikt nie podniesie skrzynki

**Comment by TheDoctor0** [comment]
Zakładam, że paczka wypadła z gracza po zabiciu go w kilkusekundowym okienku czasowym po evencie końca rundy, ale przed jej faktycznym zakończeniem - ikony są już wtedy ukryte.
Dodałem usuwanie ikon paczek także na początku każdej rundy, co powinno wyeliminować problem
- możesz zaciągnąć sobie cod_icons z brancha master i przetestować ten scenariusz.

**Comment by eryk172** [comment]
Teraz wgl nie ma ikonki skrzynki, ale to pewnie spowodowane tym że wlasnie są one usuwane na koniec rundy - graliśmy 1vs1. Dam znac czy blad zostal naprawiony, jak wejdziemy testować

**Comment by eryk172** [comment]
Nadal zostaje ikonka po skrzynce

**Comment by TheDoctor0** [comment]
Poprawka [zrobiona](https://github.com/TheDoctor0/CoDMod/commit/2df8cac568307a0c99ce6278cbb1f91dd18b69a1). Testowałem spawnując boxy w trakcie trwania rundy i po jej zakończeniu. W obu przypadkach wszystkie znikały wraz z ikonami jak powinny.
