### ISSUE TITLE
Rezerwacja Nicku

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#37]
Jesli gracz wpisze w konsole sobie jakas komende np. hud_fastswitch 1
W nastepnej mapie autmatycznie wczytuje .cfg codpass.cfg i wszystkie wpisane komendy znikają.
Prawdpodobnie problem wystepuje tylko u graczy Steam.
Osobiscie usunalem linijki odpowiedzialne za wczytywanie .cfg i wszystko dziala jak nalezy

**Comment by TheDoctor0** [comment]
Plugin systemu kont ładuje codpass.cfg, odczytuje wartość setinfo z hasłem dla autologowania, a następnie ponownie wczytuje config.cfg. Także problem z resetem wpisanych komend nie występuje, o ile faktycznie zostały one zapisane w głównym configu - a zdaję sobie sprawę, że spora część graczy swój config ma ustawiony jako tylko do odczytu, co temu zapobiega.
Dodałem cvar cod_accounts_autologin_config, który określa, czy plugin ma tworzyć sobie dodatkowy config na potrzeby autologowania - jeśli jest ustawiony na 0, hasło będzie sprawdzane tylko i wyłącznie z aktualnego setinfo bez przeładowywania configów, zmienione są także komunikaty o autologowaniu.
