### ISSUE TITLE
Pokazywanie obrażeń

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#38]
Normalnie pokazuje zadawane obrazenia podczas gry, aczkolwiek po dojsciu do klanu pokazuje okrągłe zero za każdym razem.
[re_damager — kopia.txt](https://github.com/TheDoctor0/CoDMod/files/2973847/re_damager.kopia.txt)

**Comment by TheDoctor0** [comment]
Klany używają cod_inflict_damage wywołującego ExecuteHam(Ham_TakeDamage, (...)) do zadawania dodatkowych obrażeń jako bonusu za statystykę Obrażenia.
Dotychczas działo się to niezależnie od tego, czy jakiekolwiek obrażenia faktycznie miały być zadawane,
stąd też przy zerowym poziomie tej umiejętności klanowej pojawiały się się zerowe obrażenia.
Dodałem zablokowanie wywołania ExecuteHam, jeśli obrażenia są mniejsze lub równe 0.

**Comment by eryk172** [comment]
Teraz nie pokazuje DMG zadanych 0.0, ale jesli ulepszymi skill w klanie to pokazuje DMG na ekranie gracza tylko te zadane z klasu. Normalne DMG jakby bylo ignorowane w tym przypadku.
Dodatkowo powiem ze problem nie występuje tylko w przypadku gdy gracz ma wybraną klasę i jest w klanie.

**Comment by TheDoctor0** [comment]
Używane w klanach cod_inflict_damage jest wywoływane w cod_damage_post, czyli zaraz po zadaniu zwykłych obrażeń. 
Jeśli używasz pluginu, który wyświetla tylko jedną wartość obrażeń, to całkowicie normalne jest, że bonusowe obrażenia będą momentalnie nadpisywać te zwykłe. 
Także albo użyj pluginu, który wyświetla jednocześnie kilka wartości albo filtruj dodatkowo obrażenia z flagą DMG_CODSKILL (generowane przez cod_inflict_damage) lub całkowicie nowej fladze obrażeń używanej tylko dla tego bonusu.

**Comment by eryk172** [comment]
`Także albo użyj pluginu, który wyświetla jednocześnie kilka wartości`

Możesz zapodać taki plugin?
Teraz np. uzylem takiego i nadal lipa.. :/

[damager.sma.txt](https://github.com/TheDoctor0/CoDMod/files/3051491/damager.sma.txt)

Nawet próbowałem tak jak jest zawarte w komentarzach

**Comment by TheDoctor0** [comment]
Możesz spróbować [mojej wersji](https://gist.github.com/TheDoctor0/8e5e77695e57d3fb9e4a0bb39031690a) ABD.
