### ISSUE TITLE
Niewidzialnosc

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#40]
Problem polega na tym ( testowane na perku AWP Nevermore oraz klasie MAG)

Gracz sie respi z AWP, powienien miec od razu niewidke. Jednak dopiero ona dziala po zmienie na noz a pozniej na AWP.

Gdy poswieci mag na innego gracza, ten dostaje normalnie poświatę i pełną widoczność. Jednak po zniknieciu poświaty pojawia, gracz nadal jest widoczny. Znowu po zmianie na nóż, a pozniej na AWP włącza się niewidka.

**Comment by eryk172** [comment]
Nadal występuje problem.
Nawet przy klasie komandos + AWP Neymore. Nie zmienimy broni, to nie ma niewidki na AWP.
Również podczas rozpoczęcia biegania, nie ustawia nam niewidki. Tylko i wyłącznie zmiana broni zadziała

**Comment by TheDoctor0** [comment]
![20190320215016_1](https://user-images.githubusercontent.com/16612504/54718328-8b6fa380-4b5a-11e9-8ca1-93e8e27fddd2.jpg)
Debug renderu przy respawnie, trzy automatyczne zmiany:
1. 100/255 na nożu.
2. 255/255 z deaglem.
3. 75/255 z awp.

Render jest zmieniany tylko, gdy na podstawie wyliczeń zostanie wykryta taka konieczność. Przykładowo posiadając item Kucacz render jest zmieniany tylko, gdy gracz kuca lub przestaje kucać - nawet zmiana broni na niego nie wpływa, jeśli nie ma innego bonusu renderu (np. z klasy).
W jakiej konkretnie sytuacji render nie jest prawidłowo resetowany?

**Comment by eryk172** [comment]
#1/ Proszę wybrać klasę np. komandosa oraz item AWP Nevermore. na AWP jest niewidzialnosc, niestety jej się nie posiada od razu na start ( dopiero pojawia się po zmianie broni )

#2/ Proszę wybrać klasę np. MAG, a druga osoba niech wybierze jaką kolwiek klasę z niewidzialnością.
Po naświetleniu gracza latarką, pomimo zakonczenia efektu naświetlenia gracz naświetlony jest widzialny do momentu zmiany broni. Po zmianie broni, nadal posiada swoją niewidzialność z klasy/itemu.

**Comment by eryk172** [comment]
3. Np problem chociazby z perkiem "Cien". Gdy go dostaniemy, niewidka dziala. Po smierci juz nie, poniewaz jest nadawana tylko w cod_item_enabled(id, value)

**Comment by TheDoctor0** [comment]
1. Na wyżej zamieszczonym screenie jest pokazany respawn właśnie na klasie Komandos z posiadanym AWP Nevermore - render jest prawidłowo ustawiany.

2. Przetestuję sobie ten scenariusz.

3. I tylko tam niewidka powinna być nadawana, bo posiada typ ITEM, a render klas/itemów ustawiany jest tylko raz. Potem zarządza nim już potem tylko silnik, aż do momentu, gdy gracz przestanie mieć dany item/klasę.

**Comment by eryk172** [comment]
Nie zrozumieślimy się do końca. Po prostu jest coś nie tak z niewidzialnością. 
np przykład 3. Otrzymujemy ITEM "Cien" - Uaktywnia się niewidka. Gracz umiera, staje się widzialny nie zaleznie od wykonywanych akcji. W ten sposób item powinien (nie)działać?

**Comment by TheDoctor0** [comment]
Dodatkowa poprawka dla czasowej zmiany renderu wywołanej naświetlaniem latarką została zrobiona [w tym](https://github.com/TheDoctor0/CoDMod/commit/2df8cac568307a0c99ce6278cbb1f91dd18b69a1) commitcie. Nic poza tym nie było zmieniane od poprawki wydanej 3 dni temu i podczas testów na moim serwerze nie było żadnego problemu.

1. Naświetlanie (celowo wybrana klasa Saper posiadająca własny render):
![20190322110349_1](https://user-images.githubusercontent.com/16612504/54817666-c7f4e980-4c97-11e9-8be4-f335eee91f70.jpg)
![20190322110356_1](https://user-images.githubusercontent.com/16612504/54817691-d5aa6f00-4c97-11e9-93ea-8a889e2bb90a.jpg)
![20190322110400_1](https://user-images.githubusercontent.com/16612504/54817698-d6db9c00-4c97-11e9-8474-fba8937957c3.jpg)

2. Przedmiot Cień po respawnie:
![20190322110532_1](https://user-images.githubusercontent.com/16612504/54817735-e824a880-4c97-11e9-8277-ed83a693da53.jpg)

**Comment by eryk172** [comment]
Dziwna sprawa, np. normalnie peleryna niewidka dziala normalnie.
Specjalnie dodalem sobie debugger render,

```
stock render_change(id, playerStatus = NONE)
{
	if (!is_user_alive(id) || (codPlayer[id][PLAYER_STATUS] == playerStatus && playerStatus != NONE) || get_bit(id, renderTimer) || get_bit(id, glowActive)) return;

	if (playerStatus != NONE) codPlayer[id][PLAYER_STATUS] = playerStatus;

	static renderAmount; renderAmount = render_count(id);

	if (renderAmount != codPlayer[id][PLAYER_RENDER]) {
		codPlayer[id][PLAYER_RENDER] = renderAmount;

		set_user_rendering(id, kRenderFxNone, 0, 0, 0, kRenderTransAlpha, codPlayer[id][PLAYER_RENDER]);
		chat_print(id, "Render: %d", renderAmount);
		execute_forward_ignore_two_params(codForwards[RENDER_CHANGED], id, codPlayer[id][PLAYER_RENDER]);
	}
}
```

Po aktywacji itemu pokazuje na chacie Render: 1 i działa
w natępnej rundzie już nie.
![image](https://user-images.githubusercontent.com/47436122/54836243-1d46f000-4cc4-11e9-9a03-49f30249a59a.png)


Jeśli nie masz tego błędu to zaraz aż spróbuję od nowa serwer przeinstalować, ale nie chce mi się w to wierzyć

**Comment by eryk172** [comment]
Moze po prostu umowimy sie razem na testy?

**Comment by TheDoctor0** [comment]
Jeśli chcesz, możesz sobie sprawdzić, czy faktycznie problem występuje tylko u ciebie.
Mój serwer testowy: 188.165.21.245:27415 (hasło: cod).
Dostęp do /codadmin ma każdy gracz.

**Comment by eryk172** [comment]
Wykonałem pełny reset serwra do amx 1.8.3 i działa jak należy

Możliwe że pod amx 1.9 wystepuje problem?

**Comment by TheDoctor0** [comment]
Na swoim serwerze mam wersję [1.9.0.5241](https://github.com/TheDoctor0/BasePack), więc najnowszy dostępny build, także to na pewno nie to.
Podejrzewam, że mógł to być problem z którymś modułem lub gamedata, 
który powodował, że jakiś z eventów nie był wywoływany.
Miałem dawno temu, bo jeszcze na AMXXie 1.8.1 podobny problem, który dotyczył Hamsandwich,
a konkretnie nieprawidłowego pliku hamdata.ini - przez co nie działał np. Ham_Spawn.
