### ISSUE TITLE
Info string length exceeded

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#41]
Znalazlem info w necie ze to przez zbyt dlugie setinfo , aczkolwiek ile w tym prawdy nie wiem.
Informacja pojawia sie w konsoli

**Comment by TheDoctor0** [comment]
Tak, błąd ten jest spowodowany zbyt długą długością stringa dla aktualnie ustawianej wartości setinfo (jeśli dobrze pamiętam limit wynosi 128 znaków) lub suma długości nazw ustawień setinfo jest za długa. 
Jednakże nie jest on w żaden sposób powiązany z samym CoDem. Różne serwery mogą dodawać wiele nowych ustawień setinfo, jedynym wykorzystywanym przez CoDa jest _codpass używane przez plugin systemu kont.
Jeśli taki problem się pojawia, wystarczy w konsoli wpisać setinfo, co wylistuje wszystkie używane ustawienia i usunąć z configu te, które są niepotrzebne.
