### ISSUE TITLE
Limit honoru

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#43]
Po osiągnięciu limitu honoru w zmiennej, wchodzi na minus a pozniej zeruje. 
Proponuje wstawić zwykłą instrukcją warunkową, że limit honoru osiągnięty

**Comment by TheDoctor0** [comment]
Integer overflow, czyli przekroczenie wartości 2147483647 dla 32-bitowej zmiennej.
Zaimplementowałem zabezpieczenie przed nim dla zmiennej przechowującej exp - jeśli wartość expa na maksymalnym poziomie wyliczona na podstawie ustawionych cvarów jest za duża, to silnik wyrzuci odpowiedni błąd.
W przypadku honoru powiedziałbym, że taka sytuacja jest mało prawdopodobna, ale dla świętego spokoju doimplementowałem limit honoru ustawiany w #define HONOR_LIMIT (domyślnie właśnie 2147483647).
