### ISSUE TITLE
Ikony - Wyświetlanie od danej odległości

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#44]
Gdy jesteśmy blisko paki, bombsite nie jest koniecznie wyświetlanie ikonki. Moze to irytować graczy, np. tak jak jest pokazane na screenie

![Screenshot_1](https://user-images.githubusercontent.com/47436122/54490559-1c265500-48b7-11e9-904c-ec44305a47f5.png)

**Comment by eryk172** [comment]
Nadal jest ikona, proponuje po prostu wylaczyc jesli jestemy blisko i widzimy ikonę ( 300-400 jednostek)

![image](https://user-images.githubusercontent.com/47436122/54714270-d4baf580-4b50-11e9-9882-47e2af04afd1.png)

**Comment by TheDoctor0** [comment]
Na ten moment ikona znika, gdy gracz znajduje się w odległości mniejszej niż 1 metr (39.37 jednostek).
Nie wykluczam zwiększenia tej odległości do 3-5 metrów, ale na pewno nie więcej.

**Comment by eryk172** [comment]
![image](https://user-images.githubusercontent.com/47436122/54714649-bacde280-4b51-11e9-804f-b401adea1a14.png)

Dodatkowo gdy jesteśmy przy byle jakiej ścianie ikonka powinna zniknac, zobacz tutaj na tym screenie nie mozna się wcelować w ten punkt bo po prostu zasłania

**Comment by eryk172** [comment]
W jaki sposób zwiększyć odległość pokazywania ikony jeśli jesteśmy przy ścianie?

**Comment by TheDoctor0** [comment]
W tym przypadku winna jest nie odległość, a skala ikony.
Zarządza nią linijka:
```
set_es(es, ES_Scale, distance < 10.0 ? 1.0 : floatmin(floatmax(0.3, 0.0025 * distanceToWall), 1.25));
```
Jeśli chcesz możesz poeksperymentować z tą formułą i zaproponować jej wersję, która byłaby bardziej według ciebie odpowiednia.

**Comment by eryk172** [comment]
Tak wyglada ikona gdy jestesmy blisko sciany, daleko od ikony
![image](https://user-images.githubusercontent.com/47436122/54791743-7d458400-4c3b-11e9-99e5-837e5c001019.png)
Tak wygląda ikona gdy jesteśmy blisko ściany, ale też blisko ikony
![image](https://user-images.githubusercontent.com/47436122/54791772-a534e780-4c3b-11e9-9547-5cb90d2bee10.png)

Jeśli dystans do ikony jest poniżej 10.0 ustaw wielkość ikony 1.0, jeśli jest powyżej generuj ikonę na podstawie floatmin(floatmax(0.3, 0.0025 * distanceToWall), 1.25).
Rozumiem zasadę działania. Zmieniając 1.0 na 0.65 jest jakimś rozwiązaniem, ale nie do końca slusznym.

Zrobiłem w ten sposób i działa tak jak powinno:
```
	if(floatround(distanceToWall / UNITS_PER_METER, floatround_floor) < 2.0)
	set_es(es, ES_Scale, 0.3);
	else
	set_es(es, ES_Scale, distance < 10.0 ? 1.0 : floatmin(floatmax(0.3, 0.0025 * distanceToWall), 1.25));
```

**Comment by TheDoctor0** [comment]
Nowa formuła obliczania skali została [dodana](https://github.com/TheDoctor0/CoDMod/commit/fc3cbdca07348a72c6fe5d3499eff5ff9eca72fe).
