### ISSUE TITLE
Wsparcie dla obsługi Admin Loadera

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#46]
nie dziala komenda commandAdminTime . Trzeba wylaczyc serwer, recznie ustawic w SQL admin = "1", włączyć serwer. Mysle ze powinno nadawać "1" automatycznie, sprawdzane przy kazdym wejsciu na serwer czy gracz moze ma juz admina 👍

**Comment by eryk172** [comment]
jednak nawet po ustawieniu recznie w sql na "1", nie dziala komenda /czasadmin

**Comment by TheDoctor0** [comment]
Ta funkcjonalność jest już wdrożona i to od dawna.
Lokalnie flaga admina nie jest ładowana z bazy, tak więc ustawienie jej tam nie da dostępu do komendy /czasadmin, aczkolwiek dany gracz pokaże się wtedy na liście z czasami gry adminów.
Flaga ta jest ustawiana tylko i wyłącznie w client_authorized_post, która to funkcja jest wywoływana zarówno przez client_authorized jak i amxbans_admin_connect (dla kompatybilności z AmxBansem). 
Jest ona zapisywana w bazie wraz z każdym zapisem statystyk, tj. podczas respawnu, wyjścia z serwera lub zakończenia mapy.

**Comment by TheDoctor0** [comment]
Problem z resetowaniem flagi admina istniał, ale został poprawiony po zgłoszeniu w issue #19.

Ta funkcjonalność jest już wdrożona i to od dawna.
Lokalnie flaga admina nie jest ładowana z bazy, tak więc ustawienie jej tam nie da dostępu do komendy /czasadmin, aczkolwiek dany gracz pokaże się wtedy na liście z czasami gry adminów.
Flaga ta jest ustawiana tylko i wyłącznie w client_authorized_post, która to funkcja jest wywoływana zarówno przez client_authorized jak i amxbans_admin_connect (dla kompatybilności z AmxBansem). 
Jest ona zapisywana w bazie wraz z każdym zapisem statystyk, tj. podczas respawnu, wyjścia z serwera lub zakończenia mapy.

Możesz dodać następujące loggery dla debugowania wczytywanie flag.:
```
public amxbans_admin_connect(id)
{
	new name[32];

	get_user_name(id, name, charsmax(name));

	log_amx("amxbans_admin_connect: %s", name);

    client_authorized_post(id);
}

public client_authorized(id)
{
	new name[32];

	get_user_name(id, name, charsmax(name));

	log_amx("client_authorized: %s", name);

    client_authorized_post(id);
}

public client_authorized_post(id)
{
	new name[32];

	get_user_name(id, name, charsmax(name));

	log_amx("client_authorized: %s (Admin: %s)", name, (get_user_flags(id) & ADMIN_FLAG) ? "Tak" : "Nie");	

    playerStats[id][ADMIN] = (get_user_flags(id) & ADMIN_FLAG) ? 1 : 0;
}
```

**Comment by eryk172** [comment]
L 03/20/2019 - 23:22:22: [admin_loader.amxx] Zaladowano 11 administratorów z MySQL.
L 03/20/2019 - 23:22:23: [sklep_sms.amxx] Zaladowano 7 uslug.
L 03/20/2019 - 23:22:23: [cod_vip.amxx] client_authorized: Player
L 03/20/2019 - 23:22:23: [cod_vip.amxx] client_authorized: Player (Admin: Nie)
L 03/20/2019 - 23:22:23: [sklep_sms.amxx] Walidacja licencji o numerze identyfikacyjnym: license zostala zakonczona pomyslnie
L 03/20/2019 - 23:22:25: [admin_loader.amxx] Login: "Player<120><STEAM_0:0:53726800><>" became an admin (account "STEAM_0:0:53726800") (nickname "Eryk") (access "abcdefghijklmnopqrstu")

Pomogło dodanie 
```
public client_putinserver(id) 
{
	client_authorized_post(id);
}
```

**Comment by TheDoctor0** [comment]
Wykorzystanie client_putinserver działa tylko dlatego, że jest w zdecydowanej większości wypadków wywoływane po client_authorized, stąd też daje większe okienko czasowe na załadowanie flag przez dodatkowy plugin.
Jak widzę nie korzystasz z Admin Loadera, co jest przyczyną problemu. Nie jest on kompatybilny z pluginami VIPa / statystyk, bo używa własnego forwardu do informowania o załadowaniu flag - client_admin(id, flags) i to właśnie jego powinieneś tak na prawdę użyć zamiast client_putinserver.

**Comment by eryk172** [comment]
Napisalem tutaj wiadomosc, a pozniej sprawdzilem admin_loader. Przepraszam za zmarnowanie czasu, poradziłem sobie :D

**Comment by TheDoctor0** [comment]
Nie masz za co przepraszać.
Generalnie nie widzę przeciwwskazań, aby dodać support dla Admin Loadera w obu pluginach.

**Comment by eryk172** [comment]
Gotowe

**Comment by TheDoctor0** [comment]
Wsparcie dla Admin Loadera zostało dodane wraz z nowym pluginem: CoD Flags.
