### ISSUE TITLE
Multijumps API

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#48]
Dodałem  w cod_vip.sma w public client_authorized_post(id)
cod_add_user_multijumps(id, 2, ADDITIONAL);

W klasie mam:
cod_set_user_multijumps(id, 3, CLASS);

jednak po wejsciu na serwer ( posiadam na start +2 skoki), po wybraniu klasy mam ich aż 5 dodatkowych. Jednak w następnej rundzie zostają tylko dwa dodatkowe skoki. Tak jakby te klasy nie były brane pod uwage. może by warto sumować ten typ bonusu?

**Comment by TheDoctor0** [comment]
Bonusy jak najbardziej powinny być sumowane, gdyby tak nie było, to nie miałbyś możliwości posiadania 5 skoków z dwóch różnych typów bonusu. Zakładam, że to jakiś drobny błąd przy resetowaniu / ponownym przeliczaniu bonusów w nowej rundzie - przeanalizuję kod.

**Comment by TheDoctor0** [comment]
Fix został zawarty w [tym](https://github.com/TheDoctor0/CoDMod/commit/87bc54684c1adbbb3a45f4554b67ad92e680f24f) commitcie. Możesz przetestować, czy teraz wszystko działa jak należy.

**Comment by eryk172** [comment]
Jesli zdobedziemy  item  pierscien skoczka(+2) na klasie ktora posiada dodatkowe skoki(+3), w tej samej rundzie ktorej zdobylismy posiadamy aż 8 skoków. Po zgonie, normalnie jest 5 tak jak powinno być

**Comment by eryk172** [comment]
Czyli zotawiasz tak jak teraz? po zdobyciu itemu skoki klasy się podwajają  a w następnej rundzie jest dobrze?

**Comment by TheDoctor0** [comment]
Issue zostało automatycznie zamknięte wraz z [commitem fbde35d](https://github.com/TheDoctor0/CoDMod/commit/fbde35dc86b0e65203ed8e262574f6108fe92d91), który poprawił ten błąd.

**Comment by TheDoctor0** [comment]
Testowałem przed momentem na Skrytobójcy (1 skok) i itemie Pierścień Skoczka (2 skoki), wszystko działa jak powinno.
