### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#50]
Co jakis czas sypie serwer (przy 3 graczach testowane)
```
L 03/22/2019 - 15:16:42: FATAL ERROR (shutting down): IndexOfEdict: bad entity
FATAL ERROR (shutting down): IndexOfEdict: bad entity
/home/servers/bin/games/CS_1.6.sh: line 66: 19854 Segmentation fault      LD_LIBRARY_PATH=".:bin" start-stop-daemon --start --chuid $USER:$GROUP -m --pidfile $PID_FILE --chdir $USER_DIR/$BIN_DIR --exec $USER_DIR/$BIN_DIR/$BIN_NAME -- $GAME_PARAMS

```

**Comment by TheDoctor0** [comment]
Potrzebne jest więcej informacji, żeby móc z tym cokolwiek zrobić:
1. Klasy graczy.
2. Itemy graczy.
3. Działania graczy zaraz przed wystąpieniem crasha (np. strzelanie / zabicie przeciwnika itd.).

**Comment by TheDoctor0** [comment]
Czy w ostatnich 4 dniach ten crash się trafił?

**Comment by eryk172** [comment]
Aktualnie jest okej. Zrobiony reset wraz z problemem z niewidzialnością

**Comment by TheDoctor0** [comment]
Pozostawię issue otwarte jeszcze przez tydzień, jeśli zdarzy się ten sam crash lub inny, który może być powiązany bezpośrednio z CoDem, prosiłbym od razu to zgłosić.

**Comment by eryk172** [comment]
```
FATAL ERROR (shutting down): IndexOfEdict: bad entity
/home/servers/bin/games/CS_1.6.sh: line 66: 10094 Segmentation fault      LD_LIBRARY_PATH=".:bin" start-stop-daemon --start --chuid $USER:$GROUP -m --pidfile $PID_FILE --chdir $USER_DIR/$BIN_DIR --exec $USER_DIR/$BIN_DIR/$BIN_NAME -- $GAME_PARAMS

```

Dwa razy pod rząd ok 23 znowu ten sam crash.
Teraz tez gdy tylko wbilem na serwer, kazdy wybral po klasie i error.

"Jest start rundy, 3 graczy strzelec, snajper szturmowiec.
Pierscien dość brak i skrzydła archanioła, nikt nikogo nie atakowal bo jeszcze dobrze z respa nie wybiegli" ` 1st crash


```
Start rundy 3 graczy 2xaimer szturmowiec
perkow niestety nie znam, konczy sie w momencie smierci 1 z graczy
Tylko tym razem od startu rundy mija dobre 30s
```
		2nd crash

Może jakiś debugger dodać.. nie wiem?
Mam paczkę pluginow(nawet mniej, bo wybrane) zaciągnięte za innego serwera na ktorym nie ma crashy
Dzięki

**Comment by TheDoctor0** [comment]
Dodaj **-debug** do parametrów startowych serwera - log crasha będzie zawierać pełny stack trace i powinno być na jego podstawie zdecydowanie łatwiej ustalić konkretną przyczynę.

**Comment by eryk172** [comment]
Zrzut konsoli przed restartem:
```
L 04/01/2019 - 22:10:21: 188.146.227.145 STEAM_1:0:1756319812 X2

stats
CPU   In    Out   Uptime  Users   FPS    Players
 5.00 13.93 19.29     581   124  955.31       3
FATAL ERROR (shutting down): IndexOfEdict: bad entity
/home/servers/bin/games/CS_1.6.sh: line 66: 29560 Segmentation fault      LD_LIBRARY_PATH=".:bin" start-stop-daemon --start --chuid $USER:$GROUP -m --pidfile $PID_FILE --chdir $USER_DIR/$BIN_DIR --exec $USER_DIR/$BIN_DIR/$BIN_NAME -- $GAME_PARAMS
```
/addons/amxmodx/logs/sys_error.log
```
L 01/04/2019 - 12:30:34: (map "fy_snow_pool") IndexOfEdict: bad entity
L 01/04/2019 - 22:13:50: (map "de_dust2_2x2_lite") IndexOfEdict: bad entity
```
-debug dodane do poleceń startowych, gdzie znajdę bardziej szczegółowe dane na temat crasha?

**Comment by eryk172** [comment]
Po tygodniu testów, znalazłem powód crasha. ( podziękowania dla `ENVYUS |HappyV|`

"Intelekt O'Zone" - perk

**Comment by eryk172** [comment]
Osobiście bym jeszcze nie zamykał, chyba tylko ja prowadze takie testy Twojego silnika więc wątek z crashami byśmy zostawili? Czy tworzyć kolejne?

**Comment by TheDoctor0** [comment]
Ten konkretny powód crashy uznałbym za rozwiązany, więc raczej nie ma co dalej ciągnąć tego issue.
Jeśli uda się znaleźć jakiś inny, rozwiąże się go w kolejnym ;)
