### ISSUE TITLE
Klasa Mag

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#52]
Jest problem z klasą mag. 
Wydaje mi sie ze niewidka powinna działać na czas włączenia latarki jesli gracz jest w promieniu 50 + int, i zaraz przestać działać jeśli minie 10 sekund lub otrzymamy DMG. Nie dzieje się tak, nadaje niewidkę na stałe niezależnie od otrzymanych obrażeń oraz czasu

**Comment by TheDoctor0** [comment]
Na Magu testowałem system renderu podczas jego implementowania i moc ukrywania członków drużyny jest tak na prawdę pozostałością z tamtego okresu - pewnym niedokończonym pomysłem, o którym właściwie już sam zapomniałem. 
Patrząc już po samym kodzie, jak najbardziej brakuje tutaj resetu bonusu niewidzialności po otrzymaniu/zadaniu obrażeń, a także po wyjściu z obszaru działania mocy zarówno dla samego Maga jak i graczy, którzy z niej skorzystali (np. taskiem). No i kwestia użycia prethinku też nie jest tutaj idealna.
Postanowiłem, że moc ta zostanie [zastąpiona](https://github.com/TheDoctor0/CoDMod/commit/21717884ee66963de4bf732b3ff6ee1dd76aa883) przez odpowiednik tej, którą daje Nóż Medyka, czyli leczenie się na nożu.
