### ISSUE TITLE
Sklep - SMS - cod_flags

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#53]
```
] amx_who

Clients on server:
 #  nick             authid               userid   imm  res  access
 1  Lofelas          STEAM_0:0:459218863  8        No     No     sz
```

Jednak VIP nie działa, obstawiam że ten sam problem co był z admin_loaderem.
Może jakiś set_task ustawić do wczytywania flag 1 sec?

**Comment by TheDoctor0** [comment]
Z jakiego pluginu sklepu korzystasz i czy posiada on jakikolwiek natyw informujący o załadowaniu/przeładowaniu flag graczy?

**Comment by eryk172** [comment]
https://sklep-sms.pl/
Raczej nie posiada

**Comment by TheDoctor0** [comment]
Korzystałem z niego kiedyś i o ile mnie pamięć nie myli do paczki był dorzucany zedytowany plugin AmxBansa i po załadowaniu przez flag był wywoływany standardowy forward amxbans_admin_connect(id) - oczywiście wymogiem jest w tym przypadku jego posiadanie.
Powiem szczerze, że jeśli amx_who także nie zwraca flagi VIPa ("h"), która zakładam powinna być dodawana właśnie przez SklepSMS, to zwyczajnie Admin Loader nie jest z nim kompatybilny i zapewne nadpisuje flagi gracza.
Najprostszym rozwiązaniem wydaje się właśnie zastąpienie go AmxBansem, bo chyba, że chcesz pisać własną integrację w Admin Loaderze, tak żeby flagi wyciągał bezpośrednio z bazy SklepuSMS.

**Comment by eryk172** [comment]
Mam zmienioną flagę vipa na "s".
Więc napiszę do technika sklep-sms
Dzięki za odpowiedź

**Comment by eryk172** [comment]
https://github.com/TheDoctor0/sklep-sms
Sprawdzales czy dziala z Twoim forkiem sklepu-sms?
