### ISSUE TITLE
Dodatkowe teleporty, miny, rakiety, itp..

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#54]
![image](https://user-images.githubusercontent.com/47436122/55064423-4081ee80-507a-11e9-8e91-b083eadbd802.png)

Podczas ustawienia bindow np w ten sposób:
bind "x" "+teleport;+mine;+rocket;+medkit;+thunder"
Pojawiają się na HUD wszystko na raz ( tak jak na screenie )

Dodatkowo trzeba pomyśleć nad tymi bindami, jest ich za dużo. 
Może jakiś inteligętny sposób, że silnik wie kiedy iżyć danego dodatkowego przedmiotu?
np. gdy kieruje w gracza to wali rakiete/piorun, gdy nie jest w ciasnym pomieszczeniu to stawia apteczkę , w  innym przypadku dynamit/minę?
Ewentualnie jeszcze na podstawie odległości od przeciwnika można by bylo określić co włączyć.. nie mam pojecie. Luźne propozycje 😊

**Comment by TheDoctor0** [comment]
Jeśli wszystkie skille są zbindowane pod jeden klawisz, to takie działanie jest wręcz porządane,
bo każda z komend w bindzie jest obsługiwana osobno i jedynie blokowane jest użycie 
więcej niż jednej umiejętności na raz - co już samo w sobie nie jest proste.
Te bindy są dodane tylko i wyłącznie dla wygody graczy, którzy dokupować będą sobie bonusy w sklepie lub chcą ustawić sobie umiejętności pod różne klawisze wedle własnych preferencji.
Jakby nie było, gdy jeden z tych bonusów daje klasa/przedmiot, to jest on obsługiwany jako umiejętność klasy/przedmiotu (+class/+item), ale można go także używać bindem konkretnej umiejętności.

Zabawa w tworzenie "inteligentnego" systemu, który miałby obsługiwać te bindy zapewne skończył by się niczym innym tylko narzekaniami graczy, że skille nie są używane w sposób jaki oni tego chcą.
Czasem mniej znaczy więcej 😉
