### ISSUE TITLE
Ogranicznik  rozrzutu

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#55]
W cod.inc znalazłem taką linijkę
`cod_set_user_recoil_reducer(id, value, type = ROUND, weapon = FULL);`

```
	} else if (codPlayer[id][PLAYER_REDUCER][ALL] && (codPlayer[id][PLAYER_REDUCER_WEAPONS][ALL] == FULL || 1<<codPlayer[id][PLAYER_WEAPON] & codPlayer[id][PLAYER_REDUCER_WEAPONS][ALL])) {
		new Float:punchAngle[3];

		pev(id, pev_punchangle, punchAngle);

		for (new i = 0; i < 3; i++) punchAngle[i] *= 0.5;

		set_pev(id, pev_punchangle, punchAngle);
	}
```

Czy tutaj wartość z [PLAYER_REDUCER] nie powinna być przekazywana do punchAngle ?
Aktualnie jest na sztywno ustawione 0.5

**Comment by TheDoctor0** [comment]
Value w tym natywie to jak w wielu innych jedynie boolean (true/false).
Ogranicznik rozrzutu zmniejsza go o 50% i jest to wartość stała.

Oczywiście jak najbardziej można by zaimplementować zmienny wpływ na recoil dla większej elastyczności, 
ale pierwotnie nie widziałem po prostu takiej potrzeby. Btw, właściwie zastąpiłoby reducer i eliminator jednym natywem.

**Comment by TheDoctor0** [comment]
Po głębszym namyśle, ogranicznik rozrzutu z dynamiczną wartością nie ma jednak specjalnego sensu.
Redukcja recoilu o połowę lub całkowicie dla dowolnej broni jest w zupełności wystarczająca.
