### ISSUE TITLE
Honor Bug Limit

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#56]
Zauważyłem , że w nieznajomych mi okoliczościach dodaje dla gracza 2147483647 H
![image](https://user-images.githubusercontent.com/47436122/55104896-929f3000-50cb-11e9-970f-5f47ec896925.png)

**Comment by TheDoctor0** [comment]
Potencjalnie zabijanie hostów mogło doprowadzić do posiadania ujemnego honoru, 
co z kolei dawało możliwość spełnienia warunku sprawdzającego integer overflow honoru,
tj. zdobyty honor > 0 i honor + zdobyty honor < 0.
Wprowadziłem odpowiednią poprawkę razem małym refactoringiem pluginu [w tym](https://github.com/TheDoctor0/CoDMod/commit/6d257cc28080a1449e98bb832e0eec7808c2d834) commitcie.

**Comment by eryk172** [comment]
Zaraz sprawdzę, aczkolwiek wiem że błąd występuje gdy:
1. Dodałem monety
2. Wpłaciłem monety do klanu ( prawie do końca, ok 800 zostawiłem)
3. Ulepszyłem ksille na maxa
4. zmieniłem mapkę

Dam znać  w ciągu 24h czy nadal błąd występuje

**Comment by TheDoctor0** [comment]
Czy błąd nadal występuje?

**Comment by eryk172** [comment]
Aktualnie nie zauważyłem, dzięki za pomoc
Nie pisałem bo szukałem też innego błędu, który miałem wrażenie że występuje
Dzięki! :D
