### ISSUE TITLE
Bug niewidzialnosc

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#58]
Wystarczy sobie dac perk cien ( na klasie ktora nie posiada wbudowanej niewidki ), wtedy po zgonie niewidka zostaje.
W przypadku gdy posiadamy klase z wbudowana niewidka, wszystko dziala jak nalezy

**Comment by TheDoctor0** [comment]
Przedmiot Cień daje stały bonus 0/255 renderu, więc nie rozumiem co ma mieć do tego zgon?
W jego przypadku gracz stale będzie w 100% niewidzialny, niezależnie od klasy i tego czy zginął.

**Comment by eryk172** [comment]
Przepraszam, nie dokończyłem pisać. Wystarczy że wyrzucimy perk, wtedy nie przywraca renderu do 255

**Comment by TheDoctor0** [comment]
To już zdecydowanie bardziej możliwy scenariusz.
