### ISSUE TITLE
Zimne Kule

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#59]
Po zamrożeniu gracza jest pokazywany tylko efekt( niebieska poświata) oraz śnieżka na ekranie gracza zamrożonego. Przeciwnik nadal może biegać

**Comment by TheDoctor0** [comment]
Jeśli dobrze pamiętam zamrożenie ustawia stałą prędkość gracza COD_FREEZE (0.1 - unieruchomienie) na czas trwania efektu niezależnie od broni czy innych bonusów.
Właściwie jedyną sytuacją, kiedy gracz nie zostanie zatrzymany może być, gdy ofiara nie posiada wybranej klasy.

**Comment by eryk172** [comment]
Cześć, sprawdzałes?

**Comment by eryk172** [comment]
Jesteś w stanie powiedziec w jaki sposob optymalnie byś dodał do tego perku blokowanie wykonywania operacji ( skok, kucanie) oraz dodanie modelu ice cube?
https://www.amxx-bg.info/viewtopic.php?t=566
Przykladowo z tego pluginu chcialem zaciągnąć troche kodu, jednak gdy to zrobilem - fajnie działa, aczkolwiek nie podoba mi się finalny kod, jeżeli jest możliwość chciałbym zobaczyć na przyszłość jak Ty byś to wykonał 🙏 Głównie chodzi o wyświetlenie modelu oraz blokade skakania,kucania
