### ISSUE TITLE
Nano kamizelka

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#60]
Na nano kamizelke nie powinno działać np. wyrzucanie wroga w powietrze, 1/1 z kosy u komandosa?
Jeśli nie powinno, to znaczy że działa i perk jest bezużyteczny

**Comment by TheDoctor0** [comment]
Ten przedmiot nie blokuje wszystkich mocy klas/przedmiotów, a jedynie te zadające obrażenia z użyciem: 
- cod_inflict_damage, jeśli posiadają flagę DMG_CODSKILL - natychmiastowe zabicie celowo tej flagi nie używa, gdyż ma przeznaczoną własną, tj. DMG_KILL.
- cod_make_explosion, a dodatkowo rakiety, miny, dynamity, pioruny.

I dokładnie tak zostało to zaprojektowane, bo Nano Kamizelka / Tarcza Swat działająca jak na starych CoDach była po prostu zbyt OP w stosunku do wszystkich pozostałych itemów.

Jeśli chcesz, żeby natychmiastowe zabicie także było blokowane, możesz zmodyfikować implementację natywu cod_kill_player dodając do niego przekazywanie obrażeń i sprawdzanie tej mocy. Tym sposobem zadane zostaną jedynie podstawowe obrażenia.
```
public Float:_cod_kill_player(killer, victim, float:damage, flags)
{
	if (is_user_alive(victim)) {
		if (codPlayer[victim][PLAYER_RESISTANCE][ALL]) return damage;

		cs_set_user_armor(victim, 0, CS_ARMOR_NONE);

		_cod_inflict_damage(killer, victim, float(get_user_health(victim) + 1), 0.0, flags | DMG_KILL);
	}

	return COD_BLOCK;
}
```
Oczywiście musisz wtedy zaktualizować sobie także definicję natywu cod_kill_player w cod.inc i wszystkich pluginach, które go używają.

No, a jeśli dodatkowo dodatkowo blokować inne skille, jak chociażby to wyrzucanie wroga w powietrze, możesz to zrobić albo w pluginach wybranych klas/przedmiotów używając natywu cod_get_user_resistance(id) lub globalnie w silniku blokując w player_take_damage_pre wywołanie cod_class_damage_attacker (CLASS_DAMAGE_ATTACKER) i cod_item_damage_attacker (ITEM_DAMAGE_ATTACKER), gdy codPlayer[victim][PLAYER_RESISTANCE][ALL] = true.

**Comment by eryk172** [comment]
Dzięki za tak szczegółową odpowiedź, aczkolwiek masz rację. Jednak bym
tylko zmienił opis parku tak żeby nie wprowadzać gracza w błąd
