### ISSUE TITLE
Ostatnie tchnienie

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#62]
Perk wgl nie działa , dochodzi do 0hp i zgon

**Comment by eryk172** [comment]
Jeśli zabijamy gracza serią w np nogi to normalnie umiera, jeśli walniemy przykladowo heada z deagla to normalnie gracz dostaje god mod na x sec. 1/1 z kosy u komandosa przykładowo zabija nawet z tym perkiem

**Comment by TheDoctor0** [comment]
W [tym commitcie](https://github.com/TheDoctor0/CoDMod/commit/080ea1ba4f33cf2fa8c05c1bf4336bbe655f8aa8) (oczywiście i tak lepiej pobrać najnowszą wersję) dodałem, aby godmode blokowało także wszelkie obrażenia zadawane przez cod_inflict_damage/cod_kill_player, co mogło powodować te efekty uboczne.
Dodatkowo zawarta tam była mała zmiana co do samego itemu, aby godmode był aktywowany także gdy zadane obrażenia są dokładnie równe aktualnemu życiu gracza.
