### ISSUE TITLE
Ulepszanie perku ( Zimne Kule )

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#63]
Czesc,
Nie wiem jak to dziala na innych perkach z 1/x, ale przykładowo przy tym podczas ulepszania zamiast otrzymac z 1/7 na 1/6 otrzymujemy 1/8, , 1/9 i tak dalej.

**Comment by TheDoctor0** [comment]
Ulepszanie itemów działa losowo, domyślnie trafić się może -1 i +1 do wartości.
Dla danego przedmiotu można tym manipulować przekazując odpowiednie wartości jako argumenty upgradeMin i upgradeMax funkcji cod_random_upgrade.
