### ISSUE TITLE
Betonowe cialo

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#64]
Gracza posiadającego betonowe cialo:
Umiejetnosci klasy 1/x zabiją
Perki 1/x nie zabiją

**Comment by TheDoctor0** [comment]
Wynika z kolejności wykonywania forwardów w take_damage_pre. Właściwie ten sam problem dotyczy także chociażby Notatek Kapitana. Zmodyfikowałem ją tak, aby najpierw aktywowały się skille ofiary, a dopiero potem atakującego.
