### ISSUE TITLE
/klasy - podział na frakcje

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#65]
Cześć,
Pod /klasa jest podział na frakcje jednak pod /klasy już nie ma. To celowe zagranie czy po prostu zapomniałeś?

**Comment by TheDoctor0** [comment]
Jak się nad tym zastanowiłem, to właściwie tak, zapomniałem o frakcjach w opisach klas.
Myślę, że jak najbardziej przydało by się to dopisać i zrobię to jak znajdę chwilę czasu w najbliższych dniach.
