### ISSUE TITLE
coditem_odwrotnosc.sma

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#67]
Dodaje HP w bardzo malych ilościach - chyba tylko te z bonusu z klanu.

**Comment by TheDoctor0** [comment]
Odwrotność na ten moment przechwytuje jedynie wartość będącą podstawowymi obrażeniami zredukowanymi o bonus Wytrzymałości i ewentualny wpływ cod_class_damage_victim.
Przydałoby się to zmienić jak w przypadku ostatnio modyfikowanego Ostatniego Tchnienia na cod_damage_pre i cod_damage_inflict, aby przechwytywać (i blokować) całość obrażeń, 
które faktycznie miałyby zostać zadane graczowi.
