### ISSUE TITLE
Wyłączenie mocnych perków

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#68]
Cześć,
W jaki sposób podszełbyś do kwestii wyłączania perków zależnie od ilości graczy?

Załóżmy że grając w 1-4 osoby, gracz który przykładowo dostanie perk Cien, Potrójna moc, itp będzie zbyt OP dla reszty.

Przykładowo perki x,y,z nie są aktywne gdy jest poniżej x graczy.

**Comment by TheDoctor0** [comment]
Generalnie sam mechanizm blokowania użycia można to rozwiązać na dwa sposoby:
1. Dodać nowy parametr w natywie cod_register_item, który miałby określać, czy item może być użyty poniżej ustalonego limitu graczy i sprawdzać to w silniku w set_item - globalnie.
2. W wybranych itemach w cod_item_enabled zwracać COD_STOP, jeśli liczba graczy jest mniejsza niż ustalony limit graczy - lokalnie.

Oczywiście jako, że liczba graczy na serwerze jest zmienna, trzeba się zastanowić nad sytuacjami typu co zrobić, gdy ktoś zdobędzie item, a potem kilku graczy wyjdzie z serwera i zostanie ich mniej niż wynosi limit - pozwolić mu dalej z niego korzystać, usunąć mu go, zamienić na inny?
