### ISSUE TITLE
CoD Admin Menu

### ISSUE THREAD

**Issue by dinowy** [TheDoctor0/CoDMod#7]
Siemka czy istnieje możliwość przerobienia tego pluginu pod Twojego COD Moda? :)
https://amxx.pl/topic/50969-admin-menu-v-15/

Problem leży po stronie natywów bo przy wgraniu na serwer w logach jest takie info:

`[AMXX] Plugin "cod_adminmenu.amxx" failed to load: Plugin uses an unknown function (name "cod_set_user_perk") - check your modules.ini.`

Więc domyślam się że to wina natywów 💃

**Comment by TheDoctor0** [comment]
Tak, jak najbardziej można go zaadaptować pod mój silnik.
Jako, że kod tego pluginu nie jest specjalnie dobrej jakości, 
wisiliłem się i napisałem go od zera: [CoD Admin Menu](https://gist.github.com/TheDoctor0/11f3757227477e6524c30af3dbbcd378).
Oczywiście do skompilowania wymagana jest biblioteka _cod.inc_.
Zastanowię się, czy dołączyć go do całości moda jako opcjonalny plugin dodatkowy.

Przy okazji testowania ustawiania poziomu niższego niż obecny, znalazłem drobnego bug'a związanego z resetowaniem punktów statystyk. Poziom jest zapisywany dopiero po wywołaniu tego właśnie resetu, co sprawia, że liczba punktów odnosi się do poprzedniego, wyższego poziomu.
Odpowiednią poprawkę wydam razem z wersją 1.2, 
a tymczasem jeśli chcesz możesz wprowadzić ją na własną rękę. 
Wystarczy w _cod_mod.sma_, znaleźć w linii 2753: `reset_points(id);` i zamienić na:
```
codPlayer[id][PLAYER_POINTS] = (codPlayer[id][PLAYER_LEVEL] + codPlayer[id][PLAYER_GAINED_LEVEL] - 1);
codPlayer[id][PLAYER_INT] = 0;
codPlayer[id][PLAYER_HEAL] = 0;
codPlayer[id][PLAYER_COND] = 0;
codPlayer[id][PLAYER_STR] = 0;
codPlayer[id][PLAYER_STAM] = 0;

if (codPlayer[id][PLAYER_POINTS]) assign_points(id, 0);
```
