### ISSUE TITLE
Trutka

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#71]
Cześć,
Jeśli juz jest medkit, to proponuje dodać trutkę którą np. będzie miała klasa chemik i nowy perk "zestaw chemika"

**Comment by TheDoctor0** [comment]
[Pierwotna](https://github.com/TheDoctor0/CoDMod/blob/1144ef48e3fe869545a9aeac0f124607b17f9806/classes/codclass_chemik.sma) wersja Chemika takową trutkę posiadała, dopiero dużo później zastąpiłem ją szansą na zatrucie przy trafieniu. 
Właściwie nie widzę problemu, żeby zaimplementować ponownie taką trutkę będącą przeciwieństwem apteczki.
Przymyślę jeszcze, czy jest sens dopisywania jej do silnika, czy wyłącznie do Chemika i ewentualnie proponowanego dodatkowego przedmiotu.
