### ISSUE TITLE
najlepszy gracz rundy

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#73]
Pokazuje najlepszego gracza z poprzedniej rundy, a aktualny jest pokazywany pod koniec kolejnej rundy

**Comment by TheDoctor0** [comment]
Informacja o najlepszym graczu jest podsumowaniem całości poprzedniej rundy - jest wywoływana w cod_new_round (event HLTV), czyli dokładnie w momencie rozpoczęcia kolejnej rundy.
