### ISSUE TITLE
set_bit itemActive & classActive

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#75]
Dlaczego w niektórych perkach uzywasz itemActive a w niektórych nie?
Rozumiem jeśli odwołujemy się np w perku intelekt o zone do traceline, tam musimy sprawdzić czy gracz posiada perk.
Zauzywalem ze w niektorych skill_used jest to sprawdzanie, a w niektorych przypadkach nie. Nie zauważyłem żadnej zalezności, czy się myle?

**Comment by eryk172** [comment]
Dobra, to wina klanów. 
```
public cod_spawned(id, respawn)
{
	if (!clan[id]) return PLUGIN_CONTINUE;

	if (!get_bit(id, info) && is_user_alive(id)) set_task(5.0, "show_clan_info", id + TASK_INFO);

	cod_add_user_gravity(id, -(cvarGravityPerLevel * get_clan_info(clan[id], CLAN_GRAVITY) / 100.0), ROUND);

	return PLUGIN_CONTINUE;
}
```

**Comment by TheDoctor0** [comment]
Tak, forward cod_spawned jest wywoływany przy każdym respawnie gracza.
Aczkolwiek jeśli cokolwiek ma być ograniczone wyłącznie do pierwszego spawnu w rundzie, wystarczy sprawdzić wartość drugiego parametru - respawn:
```
/*------------------------------
Multiforward executed on player spawn event.
Respawn is true if it's not first spawn of this player in this round.
------------------------------*/
forward cod_spawned(id, respawn);
```

**Comment by TheDoctor0** [comment]
Co do zmiennych itemActive / classActive, są one używane, gdy:
1. Dana umiejętność wymaga skorzystania z funkcji innych niż wbudowane single-forwardy _cod_item\_\*_ lub _cod_class\_\*_ - przez co wymagane jest sprawdzanie, czy dany gracz faktycznie posiada tą klasę lub przedmiot.
2. Dana umiejętność jest aktywowana wyłącznie na jakiś czas - stąd też gdzieś musi być przechowywany aktualny stan tej umiejętności.

Zakładam, że pytanie zrodziło się głównie z powodu klasy Jasnowidz, w której jak widzę zmienna classActive była nieużywana właściwie od samego początku - widocznie zapomniałem jej usunąć kopiując fragment kodu z innej klasy.

**Comment by eryk172** [comment]
Nie zrozumiałeś do końca. To nie pytanie, tylko wykryłem błąd.
Zrób mały test, weź zresp kilka razy gracza poprzez cod_respawn_player np. w  itemie i zobaczysz jak się ciągle zwiększa grawitacja zmierzając do zera

**Comment by TheDoctor0** [comment]
Zakładam, że chodzi o:
> Dobra, to wina klanów.
> cod_spawn jest wywoływane za kazdym razem po repsie, wiec bonusy z klanu tak samo są dodawane

Prosiłbym zatem nie mieszać kilku kwestii (pytań i błędów) w jednym issues i wrzucać je po prostu osobno, bo potem wychodzą takie nieporozumienia.
