### ISSUE TITLE
Trujące oślepienie

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#78]
Nie działa po prostu

**Comment by TheDoctor0** [comment]
Plugin był pisany na bardzo wczesnej wersji ReAPI, więc zapewne funkcja jakiej używa (PlayerBlind) nie jest już dostępna w nowszej wersji.
Z racji, że jest to właściwie jedyny plugin, który wymaga tego modułu, lepszą opcją wydaje mi się całkowite się jego pozbycie.
