### ISSUE TITLE
Błąd 

### ISSUE THREAD

**Issue by Koliberr** [TheDoctor0/CoDMod#8]
![image](https://user-images.githubusercontent.com/47156534/51932630-ccbbc080-23ff-11e9-9751-a0a53eb41ef5.png)
I tak z każdym perkiem mam 1/0 lub +0 

Powiedziałbyś czemu tak jest?

**Comment by TheDoctor0** [comment]
Jeśli przedmioty dawałeś sobie z użyciem [CoD Admin Menu](https://gist.github.com/TheDoctor0/11f3757227477e6524c30af3dbbcd378), to nic w tym dziwnego.
Zupełnie zapomniałem o trzecim argumencie natywu cod_set_user_item, 
który domyślnie przyjmuje właśnie wartość 0, stąd też każdy przedmiot otrzymywał taką właśnie wartość.
Poprawiłem już to niedopatrzenie z mojej strony i zaktualizowałem Gist'a tegoż pluginu.

**Comment by Koliberr** [comment]
To co muszę zmienić aby działały? Bo jak zabije to też wypada 1/0 lub +0

**Comment by TheDoctor0** [comment]
Przedmiotom zdobywanym przez zabicie lub kupionym w sklepie wartość losowa na pewno przypisywana jest prawidłowo.
Jeśli występuje u ciebie taki problem, to mam kilka pytań, które pomogą wykryć jego przyczynę:
1. Jakiej wersji AMXX'a używasz? (amxx version)
2. Czy korzystasz z ReHLDS, jeśli tak, to z jakiej wersji? (version)
3. Którą wersję moda pobrałeś?
4. Czy kompilowałeś pluginy lokalnie?
5. Czy korzystasz z jakichś dodatkowych pluginów?

**Comment by Koliberr** [comment]
1. 1.8.3-dev+5154
2. Nie
3. 1.1.1
4. Tak
5. Nie

I dodam że np Eliminator Rozrzutu nie działa.

**Comment by TheDoctor0** [comment]
Wygląda to mi na jakiś problem z działaniem zarówno natywów jak i forwardów na twoim serwerze.
Pobieranie aktualnej wartości przedmiotu odbywa się przez forward wysyłany do pluginu przedmiotu, 
natomiast m. in. włączenie eliminatora rozrzutu odbywa się przez wywołanie natywu obsługiwanego przez silnik.

Czy na serwerze pojawiają się jakiekolwiek error logi lub warningi w daily logach?

**Comment by Koliberr** [comment]
```
L 01/31/2019 - 19:54:53: callfunc_push_xxx called without callfunc_begin
L 01/31/2019 - 19:54:53: [AMXX] Displaying debug trace (plugin "cod_mod.amxx", version "1.1.1")
L 01/31/2019 - 19:54:53: [AMXX] Run time error 10: native error (native "callfunc_push_int")
L 01/31/2019 - 19:54:53: [AMXX]    [0] cod_mod.sma::player_take_damage_pre (line 1870)

```

**Comment by TheDoctor0** [comment]
Nie usunąłeś przypadkiem jednej linijki z silnika?
Linia 1870: 
`callfunc_begin_i(function, get_class_info(codPlayer[victim][PLAYER_CLASS], CLASS_PLUGIN));`
W logu widzę, że w tym miejscu u ciebie jest wywołanie *callfunc_push_int*.

**Comment by Koliberr** [comment]
```
public player_take_damage_pre(victim, inflictor, attacker, Float:damage, damageBits)
{
	if (!is_user_connected(attacker) || !is_user_connected(victim) || get_user_team(attacker) == get_user_team(victim)) return HAM_IGNORED;

	static function, weapon, hitPlace;

	weapon = codPlayer[attacker][PLAYER_WEAPON];

	if (!(0 < inflictor <= MAX_PLAYERS)) weapon = CSW_HEGRENADE;

	hitPlace = get_pdata_int(victim, 75, 5);

	if (codPlayer[victim][PLAYER_CLASS]) {
		damage -= damage * (get_stamina(victim) / 4.0) / 100.0;

		function = get_class_info(codPlayer[victim][PLAYER_CLASS], CLASS_DAMAGE_VICTIM);

		if (function != NONE) {
			callfunc_begin_i(function, get_class_info(codPlayer[victim][PLAYER_CLASS], CLASS_PLUGIN));
			callfunc_push_int(attacker);
			callfunc_push_int(victim);
			callfunc_push_int(weapon);
			callfunc_push_floatrf(damage);
			callfunc_push_int(damageBits);
			callfunc_push_int(hitPlace);
			callfunc_end();

			if (damage == COD_BLOCK) {
				SetHamParamFloat(4, 0.0);

				return HAM_SUPERCEDE;
			}
		}
	}

	if (codPlayer[attacker][PLAYER_CLASS]) {
		damage += get_strength(attacker) / 10.0;

		function = get_class_info(codPlayer[attacker][PLAYER_CLASS], CLASS_DAMAGE_ATTACKER);

		if (function != NONE) {
			callfunc_begin_i(function, get_class_info(codPlayer[attacker][PLAYER_CLASS], CLASS_PLUGIN));
			callfunc_push_int(attacker);
			callfunc_push_int(victim);
			callfunc_push_int(weapon);
			callfunc_push_floatrf(damage);
			callfunc_push_int(damageBits);
			callfunc_push_int(hitPlace);
			callfunc_end();

			if (damage == COD_BLOCK) {
				SetHamParamFloat(4, 0.0);

				return HAM_SUPERCEDE;
			}
		}
	}

	if (codPlayer[victim][PLAYER_ITEM]) {
		function = get_item_info(codPlayer[victim][PLAYER_ITEM], ITEM_DAMAGE_VICTIM);

		if (function != NONE) {
			callfunc_begin_i(function, get_item_info(codPlayer[victim][PLAYER_ITEM], ITEM_PLUGIN));
			callfunc_push_int(attacker);
			callfunc_push_int(victim);
			callfunc_push_int(weapon);
			callfunc_push_floatrf(damage);
			callfunc_push_int(damageBits);
			callfunc_push_int(hitPlace);
			callfunc_end();

			if (damage == COD_BLOCK) {
				SetHamParamFloat(4, 0.0);

				return HAM_SUPERCEDE;
			}
		}

		function = get_func_id("cod_item_damage_victim", get_item_info(codPlayer[victim][PLAYER_ITEM], ITEM_PLUGIN));

		if (function != NONE) {
			callfunc_begin_i(function, get_item_info(codPlayer[victim][PLAYER_ITEM], ITEM_PLUGIN));
			callfunc_push_int(attacker);
			callfunc_push_int(victim);
			callfunc_push_int(weapon);
			callfunc_push_floatrf(damage);
			callfunc_push_int(damageBits);
			callfunc_push_int(hitPlace);
			callfunc_end();

			if (damage == COD_BLOCK) {
				SetHamParamFloat(4, 0.0);

				return HAM_SUPERCEDE;
			}
		}
	}

	if (codPlayer[attacker][PLAYER_ITEM]) {
		function = get_item_info(codPlayer[attacker][PLAYER_ITEM], ITEM_DAMAGE_ATTACKER);

		if (function != NONE) {
			callfunc_begin_i(function, get_item_info(codPlayer[attacker][PLAYER_ITEM], ITEM_PLUGIN));
			callfunc_push_int(attacker);
			callfunc_push_int(victim);
			callfunc_push_int(weapon);
			callfunc_push_floatrf(damage);
			callfunc_push_int(damageBits);
			callfunc_push_int(hitPlace);
			callfunc_end();

			if (damage == COD_BLOCK) {
				SetHamParamFloat(4, 0.0);

				return HAM_SUPERCEDE;
			}
		}
	}

	static ret;

	ExecuteForward(codForwards[DAMAGE_PRE], ret, attacker, victim, weapon, damage, damageBits, hitPlace);

	if (damage <= 0.0 || float(ret) == COD_BLOCK) {
		SetHamParamFloat(4, 0.0);

		return HAM_SUPERCEDE;
	}

	SetHamParamFloat(4, damage);

	return HAM_HANDLED;
}
```

**Comment by TheDoctor0** [comment]
Dokładnie ten sam błąd udało mi się uzyskać na klasie Kapitan (jako jedna z dwóch klas, która posiada funkcję *cod_class_damage_victim*) przekompilowując plugin z zakomentowaną linią 1870.
```
L 01/31/2019 - 20:26:30: callfunc_push_xxx called without callfunc_begin
L 01/31/2019 - 20:26:30: [AMXX] Displaying debug trace (plugin "cod_mod.amxx", version "1.1.1")
L 01/31/2019 - 20:26:30: [AMXX] Run time error 10: native error (native "callfunc_push_int")
L 01/31/2019 - 20:26:30: [AMXX]    [0] cod_mod.sma::player_take_damage_pre (line 1871)
```
Radziłbym zatem spróbować przekompilować silnik i jeszcze raz sprawdzić czy błąd nadal występuje, bo error log jednoznacznie wskazuje na brak wywołania *callfunc_begin_i*.

**Comment by Koliberr** [comment]
Nadal. 

![image](https://user-images.githubusercontent.com/47156534/52080450-18a16d80-2598-11e9-94cd-4cf4930a5a48.png) 

I gdy zdobędę perk gdzie powinienem dostać bron to jej nie dostaje.

**Comment by TheDoctor0** [comment]
Pomoc udzielona.

Problem był wywołany pomieszanymi modułami z dwóch różnych wersji AMXX'a
- wystarczyło go wgrać jeszcze raz od zera i wszystko zaczęło działać jak powinno.

**Comment by Pi0tRuS** [comment]
Mam to samo, powodem jest zła wersja silnika czy pluginów ?

**Comment by Pi0tRuS** [comment]
Bo u mnie to wygląda tak

W cod_admin_menu.amxx gdy jest:

"cod_set_user_item(selectedPlayer[id], selected, RANDOM)"

gdy dam sobie przedmiot np. diabelskie p228 i ono ma 1/5-7 to dostaje losową wartość czyli raz 1/6 raz 1/7 i tak jest tez z innymi perkami np. trujące oślepienie które ma 1/2 gdy dałem sobie owy  perk to pokazało 1/3

Gdy usunąłem RANDOM czyli:

""cod_set_user_item(selectedPlayer[id], selected,)"

to wszystkie przedmioty 1/x które sobie dodam to mam 1/0

**Comment by TheDoctor0** [comment]
Wartości większości itemów nie są stałe, tylko losowe i możliwe do ulepszenia (w sklepie).
Zakresy wartości zdefiniowane są w pluginie itemu jako wartości RANDOM_MIN i RANDOM_MAX.
Jak zauważyłeś zresztą Diabelskie P228 ma zakres 1/5-7, a to oznacza, 
że przy zdobyciu tego przedmiotu wartość będzie wynosić 1/5, 1/6 lub 1/7.
Trójące oślepienie posiada zakres 1/2-4, więc może się trafić 1/2, 1/3 lub 1/4.
Dokładnie tak samo jest zresztą - przykładowo Adrenalina może standardowo dać bonus 40 do 60 HP.

Wszystko jest opisane w dokumentacji natywów:
```
/*------------------------------
Register new item and return its id.
ValueMin is normal item value or random min value.
ValueMax is random max value.
Those values are used for item description and generating random value passed to item plugin.
------------------------------*/
native cod_register_item(const name[], const description[], valueMin = 0, valueMax = 0);
```
W trzecim i czwartym parametrze przekazywane są właśnie wartości RANDOM_MIN i RANDOM_MAX.
Jeśli chcesz, aby jakiś przedmiot miał stałą wartość, możesz pominąć w nim 4 parametr,
a stałą wartość przekazać w trzecim parametrze.

```
/*------------------------------
Set player's item.
If item = RANDOM (-3) an item will be random.
If value = RANDOM (-3) item value will be random.
------------------------------*/
native cod_set_user_item(id, item = 0, value = 0);
```
Trzeci parametr odpowiada za wartość i przy jego pominięciu jest to 0 - stąd 1/0 lub +0 w itemach, bo taką właśnie wartość dostają. W przypadku przekazania RANDOM, silnik wylosuje wartość z przedziału podanego w cod_register_item lub ustawi wartość stałą, jeśli przedział nie jest zdefiniowany.

**Comment by Pi0tRuS** [comment]
Zupełnie zapomniałem o tym, że itemy mają losową wartość i przy dodawaniu sobie itemu, były różne wartości dopiero teraz po wejściu w kod pluginu widzę, że są losowane wartości i przy dostaniu itemu tą wartość określa RANDOM itemu.
