### ISSUE TITLE
Wojny Klanów

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#82]
1. Podczas zakonczenia wojny pokazuje dla obu kllanów informacje

`[CoD] Zabijajac Eryk zakonczyles wojne z klanem NaFarciePL. Zwyciestwo!`
`[CoD] Ginac z rak Cypusss zakonczyles wojne z klanem Koksiki_Cycusia. Porazka...`

2. Nie da sie odrzucić wojny
Po odrzuceniu zostaje nadal opcja akceptacji wojny, wgl coś się pomieszane z tym akceptowaniem oraz oderzaniem wojny.

3. Dla przeciwnika wojny jest kolorowa poświata, która powoduje że niewidka z klas nie działa

**Comment by TheDoctor0** [comment]
Poprawki w [commitcie](https://github.com/TheDoctor0/CoDMod/commit/cfedd9f179f5c171c64adcde04f5f9ddfe6cd35f):
1. Informacje powinny się pokazywać teraz następująco:
- Dla gracza, który zdobył ostatniego fraga: Zabijajac xxx zakonczyles wojne z klanem yyy. Zwyciestwo!
- Dla pozostałych graczy w jego klanie: xxx zabijajac yyy zakonczyl wojne z klanem zzz. Zwyciestwo!
- Dla gracza, który był ostatnim fragiem: Ginac z rak xxx zakonczyles wojne z klanem yyy. Porazka...
- Dla pozostałych graczy w jego klanie: xxx ginac z rak yyy zakonczyl wojne z klanem zzz. Porazka...
2. Poprawione odrzucanie deklaracji wojen (brak przekazywanego parametru w menu) i ogólna semantyka akceptacji / odrzucania.
3. Dodałem nowy cvar:
```
// Enemies from clans at war will have red glow (Default: 1)
// 2 - war enemies glow always
// 1 - war enemies glow except when have render less than 30/255
// 0 - glow disabled
cod_clans_enemy_glow "1"
```
