### ISSUE TITLE
Rynek Durability perk bug

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#85]
Podczas posiadania perku o wytrzymałości 20%, wrzucamy go na rynek.
Po wyciągnięciu perku z runku wraca mu wytrzymalosc na 100%

**Comment by TheDoctor0** [comment]
No tak, wytrzymałość przedmiotu jest zapisywana na rynku,
ale nie jest używana ani przy zakupie, ani przy jego wycofaniu.
