### ISSUE TITLE
Receiving item

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/CoDMod#86]
Nie daje perku, gdy zabijemy zlagowanego gracza. Pewnie spowodowane is_user_connected(victim)

**Comment by TheDoctor0** [comment]
Jeśli chodzi o gracza, który utracił połączenie z serwerem, ale jego postać jeszcze chwilowo wisi na serwerze i jest przez to możliwe jego zabicie - tak, w takim wypadku warunek is_user_connected(victim) może nie zostać spełniony.
Jednakże jest to właściwie efekt tego, jak takie sytuacje obsługuje kod sieciowy GoldSource'a,
więc nie można nazwać tego błędem i wprowadzanie jakiegoś dziwnego fix'a mija się tutaj z celem.

**Comment by Kankeran** [comment]
Raczej po prostu event się nie wywołuje jak w wiele innych eventów podczas laga. (mogą wywołać się później, kiedy serwer otrzyma jakąś odpowiedź od clienta).
Zawsze można przechwycić zdarzenie zabicia przy pomocy hamsandwich specjalnie dla zdobywania perku.

**Comment by TheDoctor0** [comment]
Równie dobrze można [sprawdzić życie gracza](https://github.com/TheDoctor0/CoDMod/commit/7ec8f4911369f57010cadecca9bc450cb710deb5) w już przychwytywanym Ham_TakeDamage post przy okazji przekazując też wykryte id broni i hit place.

**Comment by eryk172** [comment]
Cześć, to jednak nie jest zrobione. Otrzymujemy perk za każdym razem, ale za dużo.
Błąd jest następępujący:

Zabij gracza
Wyrzuć perk
Rzuć granat na ciało gracza
Otrzymujesz znowu perk


Innych sytuacji nie sprawdzałem, myślę że te informacje są wystarczające

Pozdr.

**Comment by TheDoctor0** [comment]
What?
Event Ham_TakeDamage zarejestrowany na "player" nie jest emitowany w przypadku ciała gracza, bo nie jest ono samym graczem i nie można z nim wchodzić w normalną interakcję, stąd też ciału gracza nie można zadać obrażeń.
Powiem szczerze, że ta wiadomość wprawiła mnie w takie osłupienie, że od razu sprawdziłem to na własnym serwerze i... jak się spodziewałem, nic takiego nie udało mi się wywołać.
Jeśli masz możliwość, chętnie zobaczyłbym to na filmiku lub chociażby kilku screenach.

**Comment by eryk172** [comment]
https://www.youtube.com/watch?v=0cjQBQTG8Wo&feature=youtu.be

Zobacz jak to robię :D

**Comment by TheDoctor0** [comment]
Zweryfikowałem i o dziwo tak, da się to zreplikować 😨 
Jak widzę granat wyrzucony na ciało gracza w bardzo małym oknie czasowym po jego śmierci wywołuje także event Ham_Killed, więc zmiana w sposobie obsługi śmierci z brancha 1.4.0 nie jest tutaj winna.
Jest to zdecydowanie jakiś bug w samym module Hamsandwich, a może i nawet w silniku GoldSource - stąd też kwalifikuje się bardziej jako issue samego [AMX Mod X](https://github.com/alliedmodders/amxmodx/issues), więc jeśli chcesz, możesz to tam zgłosić.
Jako, że nie jest to bug w modzie, a prawdopodobieństwo jego wystąpienia też jest raczej nikłe (bo mało kto ma okazję rzucić granat prosto na ciało gracza w przeciągu ułamka sekundy po jego śmierci), nie będę dopisywał jakiegoś dziwnego fix'a, który miałby go poprawić.

**Comment by TheDoctor0** [comment]
Postanowiłem sprawdzić jak głęboko sięga problem.
To jednak nie sam Hamsandwich, problem
