### ISSUE TITLE
Obsługa botów 

### ISSUE THREAD

**Issue by dinowy** [TheDoctor0/CoDMod#89]
Witam czy jesteś w stanie przerobić ten plugin żeby boty wybierały chociaż jedna klasę ? Próbowałem to zmienić ale co chwile wywala mi błędy - nie ogarniam do końca natywow :D 

Link do pluginu - https://amxx.pl/topic/38500-obsługa-botów-codmod/

**Comment by dinowy** [comment]
+ gdzie mogę zmienić dźwięki select.wav , start.wav itp? Szukałem w silniku coda i nie mogłem znaleźć tego :(

**Comment by dinowy** [comment]
Okej dzięki, coś sam stworzyłem i plugin się kompiluje ale po wbiciu bota na serwer crashuje sie z automatu :/ 

Jakbys miał chwile moglbys zajrzeć? https://amxx.pl/topic/163995-obs%C5%82uga-bot%C3%B3w-cod-ozonee/ Dzięki! :+1:

**Comment by TheDoctor0** [comment]
Powiedziałbym, że dość niepokojący jest fakt, iż serwer od razu crashuje się po wejściu bota.
Bez włączonego pluginu do obsługi botów crashe także występują?

**Comment by dinowy** [comment]
Odrazu mówię ze nie znam się na tym, po prostu pozmieniałem natywy, pousuwałem używanie perkow i umiejętności przez boty i nie działa. Chodzi mi tylko o to żeby boty wybierały klasę Pudzian :D to wszystko
