### ISSUE TITLE
2 błędy

### ISSUE THREAD

**Issue by Pi0tRuS** [TheDoctor0/CoDMod#90]
Witam
Zauważyłem 2 błędy.
1.Darmowy honor nie działa, jedynie wyskakuje komunikat, że już odebrałem darmowy honor.
2. Kiedy odebrałem sobie flagę t (VIP) noż dla vipa zostaje oraz jego model.

**Comment by TheDoctor0** [comment]
1. Jak widzę jest błąd w warunku w linii 30, powinno być:
```
if (!get_bit(id, received)) {
```
zamiast
```
if (get_bit(id, received)) {
```
Już poszedł commit z fixem.

2. Nóż VIPa powinien być resetowany przy spawnie, jeśli gracz nie posiada już uprawnień:
```
public cod_spawn(id)
{
	if (!cod_get_user_vip(id) && playerKnife[id] == VIP) {
		set_bonus(id, playerKnife[id], DEFAULT);

		save_knife(id);
	}

	set_knife(id, 1);
}
```
I tak by było, gdyby funkcja używała poprawnego eventu: cod_spawned(id, respawn).

Dzięki za zgłoszenie tych małych niedoróbek ;)

**Comment by TheDoctor0** [comment]
@Pi0tRuS, wydałem wersję [1.4.2](https://github.com/TheDoctor0/CoDMod/releases/tag/1.4.2) z poprawkami obu tych bugów.
Możesz sobie ją pobrać i podmienić tylko plugin darmowego honoru i plugin noży.
