### ISSUE TITLE
Błąd

### ISSUE THREAD

**Issue by Pi0tRuS** [TheDoctor0/CoDMod#91]
Witam,
Mam najnowszą wersję 1.5. Zainstalowałem boty na serwerze i kiedy go zabijam dostaję tylko perk cień, tylko ten. Kiedy kupuję w sklepie losowy perk dostaję znowu ten perk. Kiedy wyłączyłem go w plugins, nie dostaję żadnego perku.

**Comment by Pi0tRuS** [comment]
Już chyba znam powód. Muszę skompilować wszystkie itemy na nowo żeby działały prawidłowo. Skompilowałem przykładowy item adrenalina z nowym cod.inc i działa. A w przypadku klas nie wiem. Sprawdzę jutro.

**Comment by TheDoctor0** [comment]
Tak, dokładnie. Ze względu na dodanie parametru flagi do cod_register_item wymagane jest przekompilowanie wszystkich pluginów przedmiotów.
