### ISSUE TITLE
Klasy - kompilator

### ISSUE THREAD

**Issue by derlius-dev** [TheDoctor0/CoDMod#92]
Witam, jakiego komplikatora używacie?
chciałem edytować pare klas bo np w opisie są dwie miny a tak naprawdę posiada ich 9
Ludzie pisali że na wersji 1.4.1 nie działa poprawnie kosa dla vipa, w sensie zostają bonusy itd
lecz gdy usunąłem sobie wszystkie flagi nie miałem już wyboru kosy i wyglądu czym jest to spowodowane?

**Comment by TheDoctor0** [comment]
Nie ma czegoś takiego jak "komplikator", a kompilator.
Kod się przed użyciem kompiluje, a nie komplikuje 😄 

CoD wymaga AMXX w wersji 1.8.3 lub 1.9, którą wraz z kompilatorem polecam ściągnąć z [oficjalnej strony](https://www.amxmodx.org/downloads-new.php).

Błąd polegał na niedziałającym resetowaniu kosy, jeśli gracz wybrał sobie kosę VIPa a później stracił uprawnienia.
