### ISSUE TITLE
Kolejne pytanko

### ISSUE THREAD

**Issue by derlius-dev** [TheDoctor0/CoDMod#93]
Grając saperem kupuję dodatkową minę i nie mogę jej postawić
Grając saperem kupuję dodatkową rakietę i działa jako dodatkowa mina

**Comment by TheDoctor0** [comment]
Poprawione. Funkcje przydzielające rakiety/miny były w sklepie zamienione miejscami.
Możesz sobie pobrać jeszcze raz wersję 1.5.0 albo sam [cod_shop.sma](https://github.com/TheDoctor0/CoDMod/blob/master/cod_shop.sma).

**Comment by derlius-dev** [comment]
Mogę zobaczyć na przykładzie kodu jak to wyglądało?

**Comment by derlius-dev** [comment]
@TheDoctor0

**Comment by TheDoctor0** [comment]
Wystarczy zajrzeć w [ostatni commit](https://github.com/TheDoctor0/CoDMod/commit/d2a463cf37e09b05db1c466b38a2a0b7ecd994f4).
