### ISSUE TITLE
problem z itemem vip

### ISSUE THREAD

**Issue by derlius-dev** [TheDoctor0/CoDMod#94]
W jaki sposób zablokować item vip, troszkę tego nie rozumiem
Zmieniłem w itemie cień flagę dla vipa
z .sma zrobiłem amxx
dodałem do cod.inc
lecz po wystawieniu na rynek dalej ktoś bez vipa może to kupić

native cod_register_item(const name[], const desc[], valueMin = 0, valueMax = 0, flag = NONE);
rozumiem że to tylko syntax (funckja która wywołuje)

**Comment by derlius-dev** [comment]
Pobrałem również amxx 1.9 na pc ale nie rozumiem jak działa tam to wszystko, jakaś pomoc?

**Comment by derlius-dev** [comment]
Przepraszam za spam, poradziłem sobie sam.

**Comment by TheDoctor0** [comment]
Przedmiot Cień to akurat przykład tego jak użyć nowego systemu dostępu do przedmiotów, aby zablokować jego użycie sprawdzając cokolwiek się chce z użyciem cod_item_check.
Jeśli chcesz zablokować przedmiot na daną flagę, to wystarczy samo dodanie flagi w cod_register_item (piąty parametr - flag):
```
cod_register_item(NAME, DESCRIPTION, .flag=ADMIN_LEVEL_H);
```
lub dla przedmiotu, który posiada losowe wartości:
```
cod_register_item(NAME, DESCRIPTION, RANDOM_MIN, RANDOM_MAX, ADMIN_LEVEL_H);
```

**Comment by TheDoctor0** [comment]
@derlius-dev, poradziłeś sobie? ;)

**Comment by derlius-dev** [comment]
Poradziłem sobie, dziękuje za pomoc ;)
