### ISSUE TITLE
Spadochron

### ISSUE THREAD

**Issue by Pi0tRuS** [TheDoctor0/CoDMod#95]
Witam,
Tak wiem już były 2 issues na temat spadochronu jednak chcę użyć spadochronu który nie powoduje zmiany niewidzialności i grawitacji. Chcę żeby można go było zbindować pod dowolny przycisk. Mógłbym liczyć na pomoc ?

**Comment by TheDoctor0** [comment]
Hej.
Właściwie bez zmian mogę polecić do tego celu [ten plugin](https://amxx.pl/topic/107674-spadochron-by-hredzone/).
Choć oczywiście jeśli chcesz mieć opcję zbindowania go pod dowolny klawisz, to trzeba by go odpowiednio zmodyfikować, np. jak jest to zrobione [tutaj](https://amxx.pl/topic/106579-parachute/).
Jeśli sam się tego nie chcesz podjąć, to napisz temat na amxx.pl.

**Comment by Pi0tRuS** [comment]
Właśnie próbowałem, ale coś mi nie wyszło.

**Comment by Pi0tRuS** [comment]
Czy mógłbyś mi pomóc w edycji tego pluginu ?. Napisałem temat na amxx.pl, jednak nikt nie raczy odpowiedzieć. Przynajmniej jakieś wskazówki co dodać a co usunąć.

**Comment by TheDoctor0** [comment]
Podejrzewam, że dłużej zajęło by wytłumaczenie co trzeba zrobić niż sama modyfikacja pluginu, więc poświęciłem kilka minut: https://amxx.pl/topic/164450-modyfikacja-spadochronu/?p=763965.
