### ISSUE TITLE
Propozycja

### ISSUE THREAD

**Issue by xHadesSoulx** [TheDoctor0/CoDMod#97]
coditem_elektromagnes  Dodać warunek że C4 nie jest przyciągane i zmniejszyć trochę zasięg

**Comment by TheDoctor0** [comment]
Ten przedmiot dokładnie tak został zaprojektowany i przyciąga wszystkie bronie, które można wyrzucać - łącznie z bombą. Jeśli chcesz, żeby działał inaczej, zmodyfikuj go sobie wedle uznania.
