### ISSUE TITLE
prawdopodobnie błąd stat

### ISSUE THREAD

**Issue by xHadesSoulx** [TheDoctor0/CoDMod#98]
w menu jest top statów od 1 tygodnia nic się nie zmienia cały czas są te same liczby  chodzi o zabicia

czas i medale działają poprawnie

**Comment by TheDoctor0** [comment]
Top staty to najlepsze statystyki graczy na **pojedynczej** mapie, a nie całościowe jak zwykłe top15.
Najlepszy wynik jest liczony według formuły: fragi*2 + fragi z hs - zgony*2.
Dopóki dane gracz nie zdobędzie na jednej mapie lepszych statystyk niż miał dotychczas, to te zostają takie same.
