### ISSUE TITLE
błędy z consoli

### ISSUE THREAD

**Issue by derlius-dev** [TheDoctor0/CoDMod#99]
L 01/21/2020 - 21:24:07: replace() buffer not big enough (16>=15)
L 01/21/2020 - 21:24:07: [AMXX] Displaying debug trace (plugin "cod_mod.amxx", version "1.5.0")
L 01/21/2020 - 21:24:07: [AMXX] Run time error 10: native error (native "replace")
L 01/21/2020 - 21:24:07: [AMXX] [0] string_stocks.inc::replace_all (line 215)
L 01/21/2020 - 21:24:07: [AMXX] [1] cod_mod.sma::sql_string (line 5610)
L 01/21/2020 - 21:24:07: [AMXX] [2] cod_mod.sma::_cod_sql_string (line 4774)
L 01/21/2020 - 21:24:07: Unhandled dynamic native error
L 01/21/2020 - 21:24:07: [AMXX] Displaying debug trace (plugin "cod_clans.amxx", version "1.3.1")
L 01/21/2020 - 21:24:07: [AMXX] Run time error 10: native error (native "cod_sql_string")
L 01/21/2020 - 21:24:07: [AMXX] [0] cod_clans.sma::client_putinserver (line 119)
L 01/21/2020 - 21:24:07: replace() buffer not big enough (27>=26)
L 01/21/2020 - 21:24:07: [AMXX] Displaying debug trace (plugin "cod_mod.amxx", version "1.5.0")
L 01/21/2020 - 21:24:07: [AMXX] Run time error 10: native error (native "replace")
L 01/21/2020 - 21:24:07: [AMXX] [0] string_stocks.inc::replace_all (line 215)
L 01/21/2020 - 21:24:07: [AMXX] [1] cod_mod.sma::sql_string (line 5610)
L 01/21/2020 - 21:24:07: [AMXX] [2] cod_mod.sma::_cod_sql_string (line 4774)
L 01/21/2020 - 21:24:07: Unhandled dynamic native error
L 01/21/2020 - 21:24:07: [AMXX] Displaying debug trace (plugin "cod_skins.amxx", version "1.3.0")
L 01/21/2020 - 21:24:07: [AMXX] Run time error 10: native error (native "cod_sql_string")
L 01/21/2020 - 21:24:07: [AMXX] [0] cod_skins.sma::client_putinserver (line 145)

**Comment by derlius-dev** [comment]
instalowałem 2tyg temu na prywatnym serwie 4sloty
wszystko działało, instaluje na nowo wykupionym 32 i nie działaja skiny + bledy

**Comment by TheDoctor0** [comment]
Z tego co widzę, to błędem rzuca natyw [cod_sql_string](https://github.com/TheDoctor0/CoDMod/blob/master/cod_mod.sma#L5600), a właściwie użyta w nim funkcja replace_all, która jest z samego AMXXa.
Jaką wersję AMXX wgrałeś na ten nowy serwer?

**Comment by derlius-dev** [comment]
ReHLDS 3.7.0.685 + AMXX 1.8.3 + dodatki Metamod
Update ReHLDS 3.7.0.685 + update AMXX 1.8.3 + dodatki Metamod

**Comment by TheDoctor0** [comment]
Jaki to konkretnie build (amxx modules)?
Masz wgrane jakieś dodatkowe pluginy?

**Comment by derlius-dev** [comment]
Wgrywałem parę podstawowych ze strony 1shot1kill
tak szczerze sam sobie chyba z tym nie poradzę
Czy odpłatnie jest szansa że pomoże pan wgrać to na serwer? czas z serwera 32sloty ucieka :/

**Comment by Pi0tRuS** [comment]
Masz tutaj gotowa paczkę rehlds ze wszystkimi dodatkami + amxmodx w najnowszej wersji 1.9.0 z metamod R przeznaczonej na rehlds. Wystarczy zrobić czysty serwer pobrać paczkę która sam posiadam wgrać na serwer i masz wszystko czego potrzebuje ten mod.

**Comment by derlius-dev** [comment]
Znalazłem, teraz działa bez zarzutów, dzięki można zamknąć
